architecture: standalone
auth:
  existingSecret: redis-affine
  existingSecretPasswordKey: redis-password
fullnameOverride: redis-affine
master:
  persistence:
    existingClaim: redis-data-redis-affine-master-0
