apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudflared-egress-restrict
  namespace: dmz
spec:
  podSelector:
    matchLabels:
      app: cloudflared
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 7844
        - protocol: UDP
          port: 7844
    - to:
        - ipBlock:
            cidr: 192.168.20.210/32
      ports:
        - protocol: TCP
          port: 80
    - to:
        - ipBlock:
            cidr: 192.168.20.213/32
      ports:
        - protocol: TCP
          port: 5678
