apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: jellyfin=jellyfin/jellyfin
    argocd-image-updater.argoproj.io/jellyfin.update-strategy: semver
    argocd-image-updater.argoproj.io/jellyfin.helm.image-spec: controllers.main.containers.main.image
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dmz
  sources:
  - repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valueFiles:
      - $values/apps/dmz/jellyfin/values.yaml
  - repoURL: https://github.com/mysweetpea/homelab-k8s.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
