controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/hotio/bazarr
          tag: release-v1.6.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
    type: deployment
persistence:
  config:
    existingClaim: bazarr-lh
service:
  main:
    controller: main
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: "192.168.20.223"
    allocateLoadBalancerNodePorts: false
    ports:
      http:
        port: 6767
