defaultServer:
  name: mysweetpea.cc
  url: https://matrix.mysweetpea.cc
config:
  disable_custom_urls: true
  disable_guests: true
  disable_3pid_login: true
  disable_registration: true
  setting_defaults:
    "UIFeature.registration": false
