apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hindsight
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: hindsight
  source:
    repoURL: https://github.com/mysweetpea/homelab-k8s.git
    targetRevision: HEAD
    path: apps/private/hindsight/chart
    helm:
      valueFiles:
        - ../values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
