helm:
  parameters:
  - name: controllers.main.containers.main.image.tag
    value: release-6.2.1.10461
    forcestring: true
  - name: image.name
    value: ghcr.io/hotio/radarr
    forcestring: true
