apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: vaultwarden=ghcr.io/dani-garcia/vaultwarden
    argocd-image-updater.argoproj.io/vaultwarden.update-strategy: semver
    argocd-image-updater.argoproj.io/vaultwarden.helm.image-spec: controllers.main.containers.main.image
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dmz
  sources:
  - repoURL: https://gissilabs.github.io/charts
    chart: vaultwarden
    targetRevision: 1.4.0
    helm:
      valueFiles:
      - $values/apps/dmz/vaultwarden/values.yaml
  - repoURL: https://github.com/bananamaker123/homelab-k8s.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
