persistence:
  existingClaim: vaultwarden

image:
  tag: "1.36.0"

vaultwarden:
  domain: "https://vault.mysweetpea.cc"
  allowSignups: false
  sso:
    enabled: true
    authority: "http://auth.mysweetpea.cc/application/o/vaultwarden/"
    scopes: "email profile offline_access"
    only: true
    signupsMatchEmail: true
    allowUnknownEmailVerification: false
    clientCacheExpiration: 0
    existingSecret: "vaultwarden-sso"
