apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gotify
  namespace: argocd
spec:
  destination:
    namespace: private
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: gotify
      repoURL: https://charts.pmoscode.dev
      targetRevision: latest
      helm:
        valueFiles:
          - $values/apps/private/gotify/values.yaml
    - repoURL: https://github.com/mysweetpea/homelab-k8s.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
