apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotify
  namespace: private
  labels:
    app: gotify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotify
  template:
    metadata:
      labels:
        app: gotify
    spec:
      containers:
      - name: gotify
        image: gotify/server:latest
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: TZ
          value: UTC
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gotify
  namespace: private
spec:
  type: ClusterIP
  selector:
    app: gotify
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
