apiVersion: v1
kind: Service
metadata:
  name: gotify-lb
  namespace: private
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  loadBalancerIP: 192.168.20.214
  selector:
    app.kubernetes.io/instance: gotify
    app.kubernetes.io/name: gotify
  ports:
  - name: http
    port: 80
    targetPort: 8080
