replicaCount: 1

persistence:
  enabled: true
  storageClassName: longhorn
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.20.222
  port: 80
  targetPort: 8080

env:
  GOTIFY_DEFAULTUSER_NAME: "admin"
  GOTIFY_DEFAULTUSER_PASS: "admin"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
