apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  destination:
    namespace: private
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mysweetpea/homelab-k8s.git
    path: apps/private/open-webui
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
