controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/mysweetpea/zilean
          tag: latest
        ports:
          - name: http
            containerPort: 8181
            protocol: TCP
        envFrom:
          - secretRef:
              name: zilean-secrets
        env:
          - name: Zilean__Dmm__EnableScraping
            value: "true"
          - name: Zilean__Dmm__EnableEndpoint
            value: "true"
          - name: Zilean__Dmm__ScrapeSchedule
            value: "0 * * * *"
          - name: Zilean__Torznab__EnableEndpoint
            value: "true"
          - name: Zilean__Imdb__EnableImportMatching
            value: "true"
          - name: Zilean__Imdb__EnableEndpoint
            value: "true"
          - name: Zilean__Imdb__UseAllCores
            value: "false"
          - name: Zilean__Imdb__NumberOfCores
            value: "2"
          - name: Zilean__FirstRun
            value: "false"
          - name: Zilean__EnableDashboard
            value: "false"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: zilean-secrets
                key: GITHUB_TOKEN
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zilean-secrets
                key: POSTGRES_PASSWORD
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 3Gi
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthchecks/ping
                port: 8181
              initialDelaySeconds: 20
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthchecks/ping
                port: 8181
              initialDelaySeconds: 10
              periodSeconds: 15
              timeoutSeconds: 5
              failureThreshold: 3

service:
  main:
    controller: main
    type: LoadBalancer
    loadBalancerIP: 192.168.20.231
    ports:
      http:
        port: 8181
        targetPort: 8181
