apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: mcpserver=ghcr.io/containers/kubernetes-mcp-server
    argocd-image-updater.argoproj.io/mcpserver.update-strategy: semver
    argocd-image-updater.argoproj.io/mcpserver.helm.image-spec: controllers.main.containers.main.image
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git.repository: git@github.com:mysweetpea/homelab-k8s.git
    argocd-image-updater.argoproj.io/git.branch: main
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:apps/private/mcp-server/values.yaml
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: private
  sources:
  - repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valueFiles:
      - $values/apps/private/mcp-server/values.yaml
  - repoURL: https://github.com/mysweetpea/homelab-k8s.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/mysweetpea/homelab-k8s.git
    targetRevision: HEAD
    path: apps/private/mcp-server/rbac
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
