controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/containers/kubernetes-mcp-server
          tag: latest
    type: deployment
service:
  main:
    controller: main
    ports:
      http:
        port: 8080
