controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/containers/kubernetes-mcp-server
          tag: v0.0.66
    type: deployment
service:
  main:
    controller: main
    type: LoadBalancer
    loadBalancerIP: 192.168.20.238
    ports:
      http:
        port: 8080
