---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-ldap-outpost-token
  namespace: dmz
spec:
  encryptedData:
    token: AgCK+lCi0PSodOD0ZXXHhRrQwLCRQOS+ojXydEIAYVl4wjxGyw2vjQokT12RpbyOUYKGD5QltW/jnU6YvuUidZaZEszgSo57z5qhC1pNXDKyvg7wc4bTMEUch4MY/iylCt2l4sxa/9swa0kVowiTCXdVrCtISgVF2pOCAIbzx4Lo3s9jIX5fRmzqwAFv4EgZtGtQ6PIXn2k+TDhyGNEOFd06PjRi6Uf9wW6uzSZYoMQ+d1FNcz2829O2dm4IscvvX0mMsPt4SgnA+K4x+QYcMm2pQpeJd2Wqxd0rBqEpdhNzO9050fxXLaKCvjbdEzz30U2whnc/m3SMaNBkrJqUkM4HEBYseO2HJLp7TfCs6DTND4C3ri+mx5/Wf4gWlHdsk42wYUXx1VOMjZyaTZPyX3VsB1amN2yiNNqTfAQ/gZ93LZnhxKSKhxaasVqjfE/+zqBDFzJ56uEi7fmjm1wCvpFTyYVmzqdS96qWaJ69VWW3/e6hJ/1SXVm4FXWYEtAIpXHlEHBZ3k7KMq4xBKO4uuqViVhjpzHovThx0qR2NwS0Qc/gogGzb9b1940Yive8RrEjiqgx7SaEgYL6dGkMj9YlT1g2pLgTdmMVVghX1EAhpcjqH6j21aKHDSCiKR7yeVH/Q2KDmO5gvKGfYvXXjiXAj8n0+Xk+5BcfgChWkWFj2Bq/DoFHYjFYY8RXCoE5v3ocdoShp39OAw6FPlz3W87/l89e6ErAZqiDjAaUdoMZNuajPhozosMGuMyh53lXXfjAsz68fXviVsyDD7s=
  template:
    metadata:
      name: authentik-ldap-outpost-token
      namespace: dmz
