controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/open-webui/open-webui
          tag: latest
    type: deployment
persistence:
  data:
    accessMode: ReadWriteOnce
    enabled: true
    size: 10Gi
    storageClass: longhorn
service:
  main:
    controller: main
    ports:
      http:
        port: 8080
