apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: qdrant=docker.io/qdrant/qdrant
    argocd-image-updater.argoproj.io/qdrant.update-strategy: semver
    argocd-image-updater.argoproj.io/qdrant.helm.image-spec: controllers.main.containers.main.image
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: private
  sources:
  - repoURL: https://qdrant.github.io/qdrant-helm
    chart: qdrant
    targetRevision: 1.18.0
    helm:
      valueFiles:
      - $values/apps/private/qdrant/values.yaml
  - repoURL: https://github.com/mysweetpea/homelab-k8s.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
