controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/nzbdav-dev/nzbdav
          tag: latest
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
    type: deployment
persistence:
  data:
    existingClaim: nzbdav-data-lh
service:
  main:
    controller: main
    ports:
      http:
        port: 8080
        targetPort: 8080
