controllers:
  main:
    containers:
      main:
        image:
          repository: searxng/searxng
          tag: latest
    type: deployment
persistence:
  data:
    existingClaim: searxng-data-lh
service:
  main:
    controller: main
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: "192.168.20.227"
    allocateLoadBalancerNodePorts: false
    ports:
      http:
        port: 8080
