controllers:
  main:
    containers:
      main:
        image:
          repository: searxng/searxng
          tag: 2026.8.22-777ba8fa4
    type: deployment
persistence:
  data:
    existingClaim: searxng-data-lh
service:
  main:
    controller: main
    type: LoadBalancer
    loadBalancerIP: 192.168.20.230
    ports:
      http:
        port: 8080
