---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp
  namespace: monitoring
spec:
  encryptedData:
    smtp-password: AgBtNjUISUq4pJYxT5DzNWQkyHBH5Wqf2a44HuwY0bZoZhYJfIpL834sKyU12H+bgkRCvQCQ1B6rfDm9wlp4NGBjpRz+Uvo+7OdyZmm6YMaK6g/z0dKLPuJ+CgJrXzPIhb6Vvua+tgQKLneBePmOLLcmZ0kMRreZ7GFlzZL3crJeznRP//kA9f+NISFwQd0hm/c6roXsMYcfHSSCqEMgfXWAVU343uT4TdLviQGDv3a6ezRNHMEu441grDRh9RlaM1zE/RoTFRPo+stgBfXAlZhUphaPoLwCJ22ELlwREp1Ivgooo/lKGoO2QTLeZj9X24k+l6F0iG82PGcl7EPpG5qIMqZjsnNOmuZ9ukjw1fLRzdA9q98o5M4iWApaCpx6ooTvmRHMKz21WGbDAVDkcRuQENq0oBWVpmDcw542R/+dUD6+fSyPnf5g65e5MmKJRYu0yifc0dwvhItEyL5DJUL1px4736BPcQEsfL1y78eRuxqayO/B/ONj9pT3rqcGbBC+GXWw83uJT7W03Rvl7D5kCBqmLF8F+BOVWZVu+wYVM/pu7hYGKusfUMSw5uQQ/RbVC42YdH/N1UQsRpJ6ov3gnmjvEqkeiEVeexQhEq/3Io1fDldayGsr+FNyImPOLY6BW0vBNsOsRSRGC4joDFvBZn2BBS7bWlIp/tPF4kKWAU1D+ghh/emZUYjs7NoktJxRnDMegrIqcwRZ4Ei2fHdoueI1OAHUZLfxrFYiSJCWyFs0ScE=
    smtp-user: AgAQ3muQ6OFwuk2sEYgbhsvWh5VrH7Fdx9Ir0y52bEeM3ZZk6uVj/9c0kvUc1074QC9GK4J2MBngk0/okgzHy58TSGojg0qY3DIUbIFoWbL3RqECfhOrP5CUoC/FuTnOOX1ZD98nhrGGsIedJIe9RPe8GfPSyBlQ6KqhvjE87vs8SshMdB7sBStxFNtzb0nsN1+vo6FhyIeZoTnLDoUxYKQBEjJ8+h+h6PfrWWm3cpx2FQSVWvuvyPOjaDoP0hkOch64/aE+suIPrBclO7hvmsXPbjciCrMKzw+ApUjnnmwiB0EV1uhxKW1V/JrV5P3tTkV0neWjo1iWL6Ds+JR7a/Ot3Ump5mr33LxO1uTm2KleTB+7EWqv8E+EE30350ntGfb+FKDqwuE8p4xHmKec7Rck88CgPIIEirG6QjIrSuClZGNEqHyyliAa2qLWFJG2tK3XG5XF6u3wXmVW6rKUs24ls1Bpz7+awGX5J2tsbbajP0cRtDTQJ/yUEnHKQtFvWEKv3cV4tBp2RT3vwWK2D5uKuTOOUXOdZmLiM35BDRheZkDck2YE9IWD0wLDqLumh1W4p5TPnIvhJCrLbC72YsxxMuJnBsqYzJzq97F004zOyyaYnZ2+AUXNmSzggfim/leWi2tsLXA7xaxtLLEyFccE/Y2Mplvrz2QD+F3ydKP6j1D4WfHwQcG75HlQ9L2paZdBZ1bgo6k=
  template:
    metadata:
      name: grafana-smtp
      namespace: monitoring
