---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAjMQswexyAVYMwn6Rag84ulbPtOKL0Kyp0RIGa2zUh8nlta3P13OuQ5Fswq0k7o1qWdl4i2yjAgXMQq9e2/YGcqLia5G3hDLBKdgdgznCYWCYqlH04Z7jXVO0eq8HX5+hRA2FgP/q+UgHx/NEROaCbC10tYmT6AHuTQH27/DU8UhYOeaNOaahJ8QIPr5/G/E84Fwxjf1r+2bQMJyb6+7hHQqQkbfE8EEnlHKr6dRQMIGrhNVtpVzKBGDH5GFd7wfDqIB+5VnkInj0YG7aT5bbUinweBtD1BoVSVpjUay7ZVVtXkWBh+gJ5Ovrlua7Px//G/uymZ2VeZxSUKsngtRr+LqkxydWxt32nXBdDGhWuJr2jtYvNa29OogrU9AQW3jAkUO517NLDbHwxVvKf6QjxxnkIJPgMyHDs8IEykF4cEYgpuDoA3oRi28917xaTw4JhnX5ks3eok+vmoHB8P7oTeIvuVWBIajQitpjLP7PtbdsYRqvUErWD6Qvyjio7IW9XBL974q3xdsDztzD65qNYvi+RT31d62K35I/t7BIs2gGs1iDXnFtIUc9s+Sp1nWBLGrNihbi5pTUPVrRjv8QqBCiHKclYm5ZUHVVy0LAVR5CAR8V3TO9RIl8J0R1OPBfdOr5W+fbU5ZKyMykuDmtHdFu7e6sFt7iYiRVAA4O/91TpwjggzVB0cFgWKkCkywugaGbTD+F971muqqMO7tH0QYe8pB7cDrRWsfdXJPydfg==
    admin-user: AgAVyDKbuKRCzapCb78NshLkUG/Z8Fa0f9CFdMwV/wuADvwc2mGOgOww746u7Aqxp5lwlTiLQlAEEYM7n7FgN118ZwYSpoo73oXIqBoqkA0ypjapMnEotOFU6WhYQWFSF8R8np2RNgKmFTQRU9LEkN9jge9wHDacy0WjFkKExJ9Ni6i1X+xcrmh//gY/Tk7WeSY8RN6TheMFqCmrJjemezoARjPKTvpLwcum0E5skR9L7Rd3wdlnQXhwmI6EWKX2DT1fP8dicr+wO8C5cnAbiwzUUm7FJ0WK5ZTzgdci3Y1QeRmQhWvTMwuzT8yzPcBDtXZnz9vGl7CcyWWHKyaxYH4YB/W2oHAeAQm37ShUx5mOg4fDoym/HsofAXqODffV7u/11gmhzszPkYaoHGKxUyoS++aD/KLY3lwSpjIsq6UBsJ3BoPrFzYtw0NuNCKh4O68olPavz2Y0L5aLy1Qy+n4qWmBhHu+L43FaCWVOip8Z7XyhR7vHefv411HhZBmhbYGYeNDKvyj3hqDV50Oj/eSEgSlw4DqSK4xHeu92+v8b49SjccaginoCjlNvoagVWKFvIXqGgC4XM9noeVk8fOMJ6htCOK9VdOuZN0KAjNwVS1XVCWFoHm6saSKWIbPqd9HJUfbU5DxDVgEJhFchA6BKybW5HRPK8RoXD8pP7pq4t/c1YefqVrbePG5N/mzazE9dPGjYdA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
