---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: kuma-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgDSjLD1M4TUZ8gu9fwxhlWkltoY9AGo3gfL82SroDxda7DYidza1Jb12yKykUnlA8qE2fbxdLVn5PF2qSecTzRp3wav86SqpoS5HdiLcPlrQp/EC+rBks7HH46bnf2w6TORFCLVGHFptRkwt1Pp5xe+ExAbf5GXRcUIZea35r3v2VTkCY2pjOUDYc2rhfwJ9kHmnDswVaNqVnhRwdXgV804c6KX1/xVVbyCLTizqjbDDpi8rGD1B0Gt+03daWD/sWdjrXEJ7jZgAymYPd6fdOREZRwHNs/ap5lbNvdd7U+QF0PiSseiAYvqkObFiA7CNtP/Qan6TgyeveHbInn++L+Va2TTJmpTAgHpYdlUE+cu+ETZ0BTNsWuevrwR8rFReo4F09txGNJlrO0Pt/T5kER4tYrHfpsCjgvCnaxA636lfjus1Lay3rcCu0v36Yo48OLQmmFEwIt223XFhri9rQ5eoUZi6tWwOQAL3sfhiqiz+N+JwnjOdG4XbHwljW0RELAfRDLNX6gKuEd5w442LhaGjUGuks/bucXqcrvbpAV35/SHF6tx0gED74tSDoh8E7gq8EwAOD3MBRI/bmhAma+lQhqPB2piyhutrGxNPMR+GHNQ61etbquTvxB6S4fmkOjxQbAqQraoyP56iM94CnPRNxYP78k8UxLeZXYPdCq2slTv5rNjGmSblVOGh4xEANcWtA4RzKKJqA8hbm/2Cuy2Wxbp0AoLgOAQY+tCwe/CIffLCYw24O+cOxhlErn6
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: kuma-auth
      namespace: monitoring
