---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kuma-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgAPAF0OrK/kL3pfXOV9UOgZUyadDQe0L44wkg2FR0K6vaMkciDXOsM+ZBqkKTCOgP5OiDRvjnSxF66oH0l3NxBihOuFWURKQOZY0HXShwFd60cmzdakMLR7fFeIAPYnfZEik5R++16EhIe5IIoGeLGLvbIJ+PP8r+WbFC1pcF2JsnqBBNOlrczrIzmtPrGxHXMtXQTAP+2qd07ljGyE4aB8XgwMupfR8N7H/eTY7ZovTybALaakDOnvqwbZb+y2WB6VpMXFKbvSowNvt/geVFK7xX1+PixoOk5otFNkAOwZQ+iacYz7HssrP+V+g0HNcUfYFB62HDfZkMIZSG4G2YAnNsGWokqbbpgJSJEfycIIS4YwgupfsxU7H0MbRxljgJ0Vkv1XGTpPI9Bfeu67ypJISor5xODTCLNsH9GbVc3md4F3r+1ItOCmWJfI0S1ce8jNjHlsHj+LVBRngAkN84SKA4advTNYuMROp58DlTEtHBU8yp1l1AZhvG/PYz4bS1XpYJjBTMsoxw3VcqIg2sWOac2RoKaB3iD4sFmdSCwxhnbDJM7etVeby39sJhBbTobIhAwHHma4Erpuou5Nhdo2MYRiAVh/P/0GrOcAG36iJdGFYaJv/sbyGqcxP42XUyzyDPLfONK3YVRyz0gvCx7GM0zgeQ4ZTXz5HfMROr3RVNZq+aJr6ttl7l6fDFE1+ibxYipaMfCTs2F57j1dD/RgjBk2hUqGKPehBEDUptOW3Yu0Wkj2hJ/ZMM5A28vr
  template:
    metadata:
      name: kuma-auth
      namespace: monitoring
    type: Opaque
