---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: netdata-gotify
  namespace: monitoring
spec:
  encryptedData:
    GOTIFY_TOKEN: AgAL5bvn/0Vf9e/7QYFszYK3r6ESlZSUYq+tpJR0s3PyHUpZZJzcb9wzwtXrHnPONeuNJdNUq6ebamZzq0AdhgjbNZ2MEhVBi2SmfDfErXjQBrugnS1rUc7feS5KOwP+R6M0MuVyj4Z2gZjVuDopnSKnf3uQK7ABRSsrlAGfUcsf6DEFOcjF1BMZOMmKmQ6HdSSuNW94D8XKsWNqxHqqWnR90DbmpFt6sShZkJS6XN13Xf/8YuOCdZ1PG2jxJ3VwbUVVBcFru2SkkRBw6ppjnVgoK6lOCkze06qbdKAbMRBJYsdQj4BVPG7fp6VoHSnQ5bi7H4cPEGg7prOXTXz8n63Rre3kVw+7xBE7cNesU9gKubm/9YYTT6yNQvWUgsc7q8EpArj1xXBvnTInzHizJ4ChHQb0qEQtXfzh22SdA/kL3+jsTczMtvJvL034qpxmUskIFlprXwPuH6TfC/zKljGM/RxPm7rRDHGFypswoirja/8+AgfO5W8gLunwmxdIcByRlUbkCt38iNkKQg7O0s1dWK0WuYv7ZHGR8TeFJz8JskzePu0NwBjV1zShGZvyAKofK833yH7v8Z5DMn/rz/AVvMirUUwAz+MejeLvRO6yiIR3PkvqS/2f7zP+8T1m1Zz6vbAsonu+r4an3m+Rpzu3/tOCOyQanxj0pB6gG55iRXR8pr8xiw+cxm5id2PhOTnEtxC+hlCWXLnUiezCuKFn4JzwP9y4LuEKPAyQt7GmTtgDElhOcMEuX1QKRp6tiv/a
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: netdata-gotify
      namespace: monitoring
