---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: update-sentinel-git-ssh
  namespace: monitoring
spec:
  encryptedData:
    sshPrivateKey: AgDBCMEyd8J8CO0dhMJRdS/o9ngVjdwiZYScVMAe1EtN1YL15EK7mghHHwfgaoR0fgxCPwq86ZWrAwwF28DB3FFrI1JUbAKqUfUWCTp1dxgw+nCDaEOujwaKD5A/AwNy+pXTgOAoL38E2eitIXDqppog5QOsiekaZpKaSbofM/wND2xcIajBTC1umK7BdaYR8awIUBjR0SDvR84fzj8yBQxAzwMcNIp+5ihMzsQT1c4a/TLBZWZu/qehCM6h3MKCoO3wvkwomsaxXfx4mAhenO8sEQrbBbzSjSFHRBeH/Bin/GLwpXSqqacNHEKPDBKIjEqjZnHQU+g/nifJ0FdS+PzALx770nefTDtXzkHsSxymiOn5ZC7cCCBVlYr793Z4KXH37zg2bhEUNJT9XpXpr01fVwLttrGuRlDDiRgyuQCN15XMhs00C+pDaVrpJL3K3O73RT1k5hiwlj9TlIFjzFXHTSgOOwUMxSAPALzSs4bRbUOH/iAgAnPBSrq+uBJCEAu8IhOM+3sapPmM9D88wrWu9GJOGe0tlqaEPUeQEzwfZoEAVp9BYCaNhoWp02c3O8Iq3YEnni2sQkSZ2KxiK+ZCrpAK3IqHTABCP3VRlM4CHRCb6Erq9xViGs2LuIJSeQcmDe7qXUyqp+cbE0sJma4W/0B9OuL75SVTF9obOi9Pz1WEiAoaofoNaG5KW9O+mwbzg8rpo5N1Ksf7mx9TmutJQhbPnoP5aNOciCftGIMJK8f3LYN6rNoZgWq4dslWkDNCewoGHJOh9QEiiyHySQuWhnI6iLrpZjj9YzP7qu/kJRgAW/7SA5eSelk9j+qGED1n9plJ3rH82/ZMY2Tw8U/r4havJMYq2XvariwNDt3S60eusmMMWuok7Xpdikasz2iBYvWpzVFgDXaUksmNV4QGt1Blbk2tHnZyrv9kpHJNOuQZL1V20PBhvq3z2Ol2eCFzDHTg4ckVbRz16BqEHIqEFhKq6MAHxXWrLOUo8kMYUr498YUDV2Wlu8+CPidfYWBZkdAaVKBirAQP3Qy5cbr3qpJIdktW1FrAClbKrNMK7BTiNastnsjGq/0lywNVAhupIVjCyYwubp76qFH0I2RreqcFkXnAx6yQPatR7MiXwoRnoAHXHoYz3oLkimlACi4MK8DjW9nWUEebKERsN7h3A1/Zq4yBt1R99KN3t0F858+LIWYkTFS8ulKm5JsFut1Yoai11dNRwzOIVWp6JuzykBbqYZn/oIvh9Pv132eLHRLVscsIQbqmpvT9p63/ZeGbKbMGOg59SLmubn4=
  template:
    metadata:
      name: update-sentinel-git-ssh
      namespace: monitoring
    type: Opaque
