controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/androidseb25/igotify-notification-assist
          tag: "v1.6.0.1"
          pullPolicy: IfNotPresent
        env:
          ENABLE_CONSOLE_LOG: "true"
          ENABLE_SCALAR_UI: "false"
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 512Mi
            cpu: 500m
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /Health
                port: 80
              initialDelaySeconds: 30
              periodSeconds: 30
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /Health
                port: 80
              initialDelaySeconds: 10
service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 80
persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn
    globalMounts:
    - path: /app/data