controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/hotio/prowlarr
          tag: latest
    type: deployment
persistence:
  config:
    existingClaim: prowlarr-lh
service:
  main:
    controller: main
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: "192.168.20.224"
    allocateLoadBalancerNodePorts: false
    ports:
      http:
        port: 9696
