---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hindsight-secret
  namespace: hindsight
spec:
  encryptedData:
    HINDSIGHT_API_LLM_API_KEY: AgBvHtrJu/QSu/RBJ6DsqY+7CZpu3vN8o5D00n/OmRMJR7+0LJk+Be7saEI1o/ReP4siJcq1HaOFiJs+9JPj4e0qp/BJtfgMKXw0Q7quYoTkMn1/mx9V6Bs2YyuJmA7Bw9dhKbx3elE5R4B04R6BHMITPGMpcPW45WQjs9QhWeJqJpXOZ+BQcbH2svYg6WPXTCOLB4WkfnYYYzOnNiZw+a1l1AIKroh2X5H1xh2NiqkNjvWkA1yVpWwVojXbeVwre1UhtXN/7xfIaGJIj9wUJt5bicYEDCoWSsvod52bmYEkKxxRB7N4p04uvSAV9F8T9/J8+RDOVRgrREmb8q5AW3tgh8aPpnbTdpWAM4H0tGQ2qB3kgGLQQfHZf9sPBGsAnttD1dpVrnntJf2RwrYSaZRSE0jbl9GatgfjxUkBl6ue/WXNETWFK0tRR2EMwO+Z9asrCIg7etXpSUW9skVl4hgXEDjouUis79rSPLdBpVKQ8pny3QBV2FH2TDE02IawS0z2OAgVEiHMJcxek0PxrFfCA1cRY7qPk/Ngb4WNus7nXjrqa5/Y4Zp5xyb992BCcXsAnbLu0bhXFjsl+08WMBuBd/am7lRZl2rRsaeRfv1HR3I4sRP0nhIe4QzlR8MTHdtVd7YddWFIls+BhjbspP9yKbFJ9EIpWcxn3k3GwwykKL8eQVSWVhqy4ehiqzguKRxZO07mLS25Vp4apbHkOtTg0gw7TAQhwQmPPmOygDm41Rqv8nLBMmXqsT+9CXwCp8gxlU2R0vku4Bs=
    postgres-password: AgDUuw9FMfyRDa5e4jsVIKC9ZsfrkMYjx2xXv699wBLNPWztwmmc6io1K9LPRSlNGTTl6X0KGhTnGqmddJ6rlz3z4xrZ6llfTRupmZwGaO4mAUKFILpsLoRqAAXuGfNWEPkzPrbXVFGkPaUjBiAcui9FylTZuagq+MzhsC2avqwRP5x9jeMe960hXaiowfiQTFVx8KmEqNR8bHhNtGSu6Qamo4hICq91OT2PWhXz+5lf/MppbJfmQM3rsBxeKm1naQlLmHQO6rb+NQ/QGuCovFW1lXQXd1If8hRh5ODFZSZL3cPKA+4NDkNbI+nUG+gArBOW8MRnYjagkYpMAoSAoWiVp0qDC1CTgwVsqHs6qeaKfY/UCvn0qgnrXFQoBKOp3mIkynyc96Hl9oPsQDHZLsrQRf6BY4LsLurutFk7BoriEbYZkK+5emWdrLBY3FVBy8DedOIBuQX2qTNtRJvyPilKKS5UaqK1GfGv7mAPcznv98vK6QiMvH3SOAHDWoF56ETSVm4LeD+fuyDHQFT4FGmiruajEjEm11i9PkMAeJ8QxMfyVXz1ELVcRh/AMaw7NW/fABBypRYmqRbgtYEcBBns+1Isny9/aUNMEaw4oMY6Kq08h9dG0ZddVbYTUtL2g/lLVGiHu3adqd29C6iTBxFS/ECWlxnskHy8jVonEJo2wqBDhHUPyUbsEmhVWTjLhXDrSnpHZyqckwTK7w==
  template:
    metadata:
      name: hindsight-secret
      namespace: hindsight
