---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-creds
  namespace: private
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgCBbf7e+cN1uxCxH4Cy7yl+xXBsaZLYSc3GwdG7jBNKosSfIk9uVwHMApP+CA/ajhnUDhpa6KQs9h8rwZ8g2KtPNX2soaQbFKcl5+Lb17yw4BxR+OR8dvljrWHZ0nBXjIJUHMepXGTep7MaqE0RjtT/szcUwp8jRZtuxNt+Af0I7KMXWLVWrYZOnRCTOPkvVYIme6MgAREZfGSOOrXgnIaLNPFsLHGqxCsfbwUla2OmxLHFQ2tGjVaiFsqUNo3tHxWTqdOpAK4SukGI37kGIp/l0GIK6i7zaA+vpPRLj2EFHuvjh0f2EMpkwYyh4xKnCeKZ94ao43umBtE375A8QdYo82eHQ4xQptimiZdxzyn8GEQDY2MG/lRAPR0Q6xhROsXLYpsjpFnrkp9maaloaDFqRZ23BIJ2RaNm5Qh6+Q/7tO+KfQlGJqEzY3X1WewTix7UcX2wN/QKERbHN0dw9Erqpf2RYhGRC6Ywu3RjA74Wz0aoDfVqVXJuPa+hg00UmnqU9TbTG8lPZcj+basjXoE+2OdLSXjgZ+7XsEL6Khovc6zpVWLIuhDCW/7bW/bQfUfuMhP6RvWklT8AbEtarkBqE5wFhFRSAHP3qEWq+34yxyCH9nonpke/eRCnRVI6yjqHImMVQO5oyJ8GlGFZ/QSOZy1WTnw1zGzwyJ3X/EKbzmXIN0LxYQsfwDFvSVT4bDRiHH0zFkinyIVhOpGaAbTcy2BLpw==
    N8N_ENCRYPTION_KEY: AgA95Y7OywofaYtD99zyPxrH4AcTGmt78WVHGot0jCYOCi524nayWGW7dOLbZNByNOb1iexWan2+d6JUKppCksE0QqBKvjBktnfzOEy6+Yx8YnbHUeiwAj2gyW9WxrNEo+p9dy44s7y8QrYc+qKxdGorWFRx0Ndpx9bE7nuVlkJUbqDxqMxwpHjMkxqhBY5UqJ7hPrq9vo/iiPgVaAtLHjSJwp6fVPGX7Xhp+w5rNGTLcr1c0DWDH7ov75rKWbbGjuXgXAIkLKRcP0haSKrbnxI1nQcBS5sjZ8oaXuL05K5rqm7rVNMsTIkbD9d3pO6yGOdjLmkN/blmqiBEDYrVzvSwr9B10O8mbMgvxAg66/3WWbkqRteVpf7VN5xiK4imR9tQzfJ+vcOl9tDnH13k3Paf4ON4JMWocHeVRgHM9MpUrKNxzr1S+2KrBTGsJpJfcktagJASVOqSV8AOaEe+IYNPKNhd98ka2/o8Jy18scib5GbwqNfuPEnY4kVqbpXdmjS5/p7JTYBLth4XPlvBQ9OeYKyqt+NaJXr9UC4+3+Ei/j8yZ5gRxGcdCChFgAAEyAUb+172jP5E6LPr7urJyk9uDRyclLANfLbcoQD4iCX3NayfyRzQi2/VV5jEYPW44RcYDKhh/wkFP7PDpqQAdbFnZaDB2/UXdsS/26ai10JspgNkjCkS8PP9jrKT6H4X1iSY7VaxJfuxEBt5ihmXnXlQvj99LcJNy+DtddM/WQyY5WkjmEWMPAy16EkKPX9kidBWJTOUM9b16g8OkSx5BW9R
  template:
    metadata:
      name: n8n-db-creds
      namespace: private
    type: Opaque
