---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-creds
  namespace: private
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgBhPID/k2CT1rjGhRHLHBVzJc1p9T9JGNJ6glsfuoVSA2HU8vqcG73bSIbFWJmSUo0cxuooFFTtwOl8Vq18D9lYPKbAf/dnvFfbqmYWlspUWdLXzcLiVpwp0FI8i/vosCX7tpZhZAOB1ouAHMfd4hoXY+txVkIKCBjoTfy1mcNpy1yNpmm2fdy6IodXTlC3E8btSIb+W2k+gRiK0F8ZBG3MKu+UC6VDMuA6BpTksEqYuJDwrY1X/R4IaJww509cRs17r4Cj2MgPXZjA2axdgoHdZHarTP1thxWmZem+SVyMBvgAaXE0QvgWF+7L78sKL9kAg6q8E+xYN7kPaNAfU0nD4fmi31mJu6anteNaOp/EcUsOHZOtwEzDv9fEOEDRk+JzAEgQFWmd5swnTISy72iRMJL4zNeknOrwlBVKnTdsMU1eTpYMqRo/1denPRX+H0GCETPzxMMr76lSkpvATH6HSKz0GHxgAvqxktcL2IP4ugfhAhjkbcFIJj7SkDVkHHg8sGBwPI+V7vb5+4GnbUCCfmpgMPnLwAJL/e8T7FG8PJ1QXeVmnkkJ5gsUwbl4hP01eAVditN9F4agxLYIIv7rXIiBb9wNH8dm+dUarroVNQ7Nnla0L1uIDY1zzLuMzWvha4XElzFUzSNzvnxNqiqQjmDMzZv5lClFwwPFF0HR+ptEZOc0InYHaxmKoBiGlHFVXLWjM2Cb1YtdvDupV5Q4HWZo7Fma2W8=
    N8N_ENCRYPTION_KEY: AgAkjjlbHv5NO7bSdCnp5K3e9ev7EXAfc5LRCNfSPh9uf/6LGPBCyXhBYDdlyksd4zCW6nil23nTHk8cAEN7osddT2eyxi9l8ibWYA3MJWuurJkKQQ2yzYMvSx+Pgw8PQyr0H9atozbpQHn/9GgLVuAYzrloXpVw9eaqgPgRJGecWqpEAFt7/MKfpibz/aeUmaHkUuVkUcXJGQqEcoKyDi+Cfbwriek1r1YyrfPOhoxH/BQx3wu+zpjB7fpIXgf4HYNjnfm58/6XSAmqi/lMbxVd1/XcWkyCjqRp9wSvq6NPhoN1KWMXkiA9t75HuK1M2KdNFTuBa+9VLPsN0lbpVBvncegG/9lmGd+8BUU3btC7O6IuRMN8leOqhMJJbIBjs7RVZuLX6NKOQBVC/OXoD1q6YlmXI6GNV7DiEnSTgH7tnptNjzJm7zPqSSz9puXIaAeJTYu8wpJrK5isynW8GMNYPIkaNEtDQflRj0OufWdQg92QebIzEbnUl+uIPieV0SZBaEOJOJG0JjjZziq/q4lRedX+qDwmoT1jTdxRJ2cAPo0VR6OZgrXhbM0/ReBsJY58K0FMy2BbFcRreVRp429D/YMT3UvJhwe+v39oaAfs1AEyXCxYiqKxk+6NMWMmbFd8Gip50XR1iNzJ7HFy9Zr2bRs3ML82HTF1HcqKY8yEo/bkaDRIf4F+NffOPW0+EY67BFVNSLqm/tIewi8mUnjXmjq61JAMyIQpYKJEacV1GHFOumQluBVYEf2PObz2feiwVo4kfQu7zLxW3uHv7Ie+
  template:
    metadata:
      name: n8n-db-creds
      namespace: private
    type: Opaque
