---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-creds
  namespace: private
spec:
  encryptedData:
    password: AgCVMOpjqSHABHtbv3CXhI/bzC/D0mZfkWchymfK+SsUDJz6/LUcgvj/iOaxiiOUUUILOnTDBZC0eSmXAmAhIjE26AHYKKWA3SlgyVXD2Mn9e7uEhGXwLkG5PRw81cGcALHExlbfXv3srcGQvmQFxRRs/WC5t/GvzSHIqRK4i4N7oOdfTWhFQx7mIVwlRPinXLYVeOSyD/A5V78h0IFWiHC8PemZOfAkQfCSbXEc40SDBiVIBT2OWdzgJ1BCRci85BrYUjLAw9SernsJyYXb58sTRsCKV6imJhI7zjJ8A2ve1Fh73XbErsw/KWXxkrTUC4CFk+Q90AEGh/o1jDiRIFzMR0wfDUeevOwv/5gV1G3uPczeVE3aKJtRmpCnjABwY1EjTwArWzKNyKekJoIJQSN0qpb4GQX75Fp1lcVF4eU3ZVPtcxBDSctXp5OiQabYd3G+Zp6jh3aP6nMtnKSOJ7WYHMj8QDP1ArjWWfkafPtNJuBqS0l410fCpMMfLBiL6uEjoBHN7QPc7xcSidEV2kzHunM/FUnjpis2zHbrrNoRA0THvk+m1BOTT+IgmYvWPuGTM/x59a7Y5/w4EHfNIHWGqZvtLXVanfjPlB9vFOz0y8Z8gd3Xh0fzyEYC+CaWblyOposW4xlk8S4oTBHPSopU8klMhhlG+PZ8mdxkh8F1f79uWynSq2jCKpJzWxTktgDRhB+063w8CBsE
    username: AgCmHj03fxyfztqZR2GmiGyRmw9Y6osib/4ok/0oVV5ibxe22hHqBFK6rvPqNI11sV63Yk42JCwaeOQ/oKTtudURwJeWiWY5AzttOIJkaCr7LpbRuZsBo0qUO3YGAeeICyxfNTantb1GZYgNaVD6/XTOwWxzW0GzJiOWnW8nkHloqqx9WxnDPMosvnAXV37uTYbsdNa7ygUDBl/jKH9yVfU02I5wghgWcDThiNAWgheSUy3Zw7MRGx7y/yfVeW3mVjMBaM67WSdW2IxLeAFEDri7opDWZP1EuSIkpr82X57lh65TLjruVrGs9oTR5Z8Rn0KzmwJdi8aqLOksJr6WrlTKBDICk72XCBEBE9YVo0bynyKGCsSfGPyAlUSXm4sFMeatAHOCUgvKofNN76iNECBszxtuqe8YEyqFepyZWysv3HNgfdWqz5USFAHxEgVcuYecvwwl9bxkZdTiBu0JuSJ804fkIe1NoOpzXH4yMS7kk7tEaE2cU34SdP/iAfI1lzA1lHNkb+fZ4eq6xG2OjtK2D4AVbTHU2tq4eyijmURNtNQIDXs5V7e9vW9knLM2SJD577hYojS/WGV/g35E2/wbyQvN12PkwDARhtL1Jf3t6irmrcvbEq+yg+vzcL8quZhoJ+7M/bSBb/Se9l4HY1SSpN93e46bTZlqm8GqZ5vTYZhr+yoxm+1s5aG4WFGhGyM1Qbr0fQ==
  template:
    metadata:
      name: nextcloud-admin-creds
      namespace: private
    type: Opaque
