---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db-creds
  namespace: private
spec:
  encryptedData:
    password: AgBaFdX9YTqnNzvkff5yL9B1dTIYnWOgl0CJtJHAIjU/GfFRwAyA4YdkbHjthf8SDEIyrycR39PTq2yPKdsU72EWJkkr3emBGgGAzaHThV6cRLepVmNdfMJf/LujOdTqHK2GIjH5ERUTYnFZXysEb/rMbHOLL57glrpzrkWfdP6sszW6kFUiPVebEO/kZra+3LadbWtBhIWXBCT6XWkM5RSG+me5CNQ5Ct9x0RTvgQJz1HxBtEVVeXYj+9FIlM8Noe+gRXW8JY4ePaVoKQd00imqwIp5q7m3ObMxcZnXMvTHv9FzSmVTHY1gAkS3A7NBUgQGWJ5JxD8EjggdQpk+3Zl869DZ2nOY2q2rNMVv3uptpUwheJyH4ikLe+Xk8KVm5RMQIRb2xob8OEkmH3aDkyPPo68Le8LARJAXSQbWUOV6dk987/rzpibZbpUk4ETWzOAXu46NtJABn74+BPmSEIJdE8dp4scmMtX6gtDNat/s7MC7NhB7G1/FaPkuDdZW/AcW46eVTHwnfueoOwkebuBNrjIPHRIze+L8h+Zu8aHZvk6qsynCJWQ/hDEfgZzIpgWd9lPya1MsGplh/nKB7wiMSX1JKXnv0CmSb5CiBhxj46DuDTUI7QxcEWUv8ha1b1ufWPbvwWDJPxOiyYmwejNjm85msRfBoMXuiG1GyuR2/JnvgdMeQkNt+lKwQi4SOmSNwTgiwYxLWVyNF8TUAL9VuM+pPkQbXQCttIjsbx+SbQ==
    username: AgA0DONPfoDMvrU8co2XzOOXwq8rKjlXGv71ASjGqxNGlYT4LWzMrkCGlzqy2NlEnyt/ialZc+M7LWU1ToZ2eC6tyaHjOCAZJm30UO3+XXkVYfAqQwLfUZS5JRq5OHpRGsrc8u4RHgXWBQTbdmLwuVrwbDY4rHlVaOd49eql52VixYjzC9GBoVxwCWE+GpStG00wmvqytW+0SaJvhJZLVOaTdcIfhoYysuo4+dvvByIpVWxzOpZa8j/uzuXwVqOEOcjP4VZuhVs4+28Q0XZGcIPg9PmcoAaq2dYjOIUXrzSuF0ddgPxCJ8aIiM09yHd1J9h5qLHddfi2WDRBZ2PsiZTOmSAhvjv7iM/V1vy7auBC7PBALWegzXHG64n3b+FbNVFP3QtHsRT5FNxGuuL6WKxukvkDE0A2Ij40gWuUKc+JyMHdcHVxfylPmR+nuQNiAGFFIU4cN7Nspfv5EvBzl3zeTg6M5Pki1jxto3wJfI7ZtGDe3xlilwyLy4vAcA7t8HTcxmdT9xUs9mdhNp3JHFMqvB30lTcujPzvGJvGzr4tHMt/XVDyE80KVMUlvUy7nHaJGNIPmXvxCknk+pae1tdkQ8P4TQLqLTTpdq5421G6v6wMx7z4LuOJvw7icP8hYLt46L9rQaaRtY8fdmZdcf94XWW33qUoIsnOQPKHfKmWBmJpWldEjQN03gKU6J9dN41xVBhGboFG7TA=
  template:
    metadata:
      name: nextcloud-db-creds
      namespace: private
    type: Opaque
