---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql
  namespace: private
spec:
  encryptedData:
    postgres-password: AgB8AjL0AW77zUP/e3uLQRX7Ds9HC/EL8ZfZjiDjBDkg/59gWSlQ7JBAPfv5qIKvWJdgxipxG+Y88i1CqhJAJ0uZpRDjDCJg56OQprMX5IeN22CVjzzKAVuDhvnapVSnfWkPSVVp1YiFX/QyM98UMUFdljNnMDhOSDmCoSqOvVpEMZiZ4wUwXt5M2bEqvif3FOGUciw4RrABdtuT1HSWzbhoyAIFWfOtd5jPHSYi0ygAmkH9L9UdRKbn+T7hH5/CfGEo3cy/4yEjVO6XSt8i5zE30BhBQN75RHSrVCksEURPFDKiv962G8cbM+vyMehIcbe8rxD1T9kNs+buFPT6Uu3H0kbzPpgYOvE7fKBB6xq4h2hoJh/W7YKweXuoilfpzWd4Z2bY5OreLmWXu5PtyGs7DUw6Db9hUesQ4LtI+u0k2Ir360LToWpMGenmHLCWGudsNApEBCtPo5S2KBd1n1HPSeVUrN+769HXdS2QF8W0SXP+JVB9j9Ea9L30P7ACKdNYxyumUJF4v0jg4kBN2BoLE2/83kfcf/1kF9Bn3AdJGIemgZlaP/t0esW090mmfF995U7JkuPe72xZeSVdUSPqBRK+U2Y4l95ngR7umFCIqGfloifw/Gxojh1EijGZs/dlNJ8TZoPQ90VmVFD0m0oMNF4JcbAgqiJYxJNTKWvGCixbs0ugIZil0dpPHT8LCqcgViqqUjPP/sXqs6ELnMAK0NqbYMiGM4w=
  template:
    metadata:
      name: postgresql
      namespace: private
    type: Opaque
