---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-webui
  namespace: private
spec:
  encryptedData:
    QBITTORRENT__WebUI__Password: AgAQEmcoo8xmBUpWePE0a6P1dGEMOddFYBq1mNCE4SAygDRIrPc7EndY8FSSRY2CNOUkRzeyGNboCuGWC29EMlQgp30UsmdP+6vm3OUnE0OdSu6AOOGOEIrmNvJvVprSQKTM64TnGl+2FaE3zKj5mo7AH0bEvZk/9WS5M+RtbPzIt8kiVkGxHN+GrRTnft7vUy4eHhBzYEosi5YHAEd+d3a2EP3og3/+uBisiOcXL0ttprVDPQ/KXpn41k3BVm1ifZfZQdlGTswtlW3PWoc/BQv7HTkDZ4sQRfzWfx6WjTFJ/DUG1CWiCg/sEeDQBQdDn32qzeEM1F/BIIjW+G6N5hM1WvMALBiG17P0BszJrBS9dY0HPmmflzpCjFCWVWBzdIfSzQa4fB+v4dvqcwxRkvgujPegy4HnGF76+MRACUii0DhbB4VcrZtfNWMarzZfKTVEPlMbbgd5PloUuZuAx1JGTswTAJTFSgsq39jncXSYM54v1Q6pZKvkldzCS6XRQdhfbVR785spZ0o/8H/EK3okG97yxJKt3Z6uiWAN+s5WNpxtSoC/JypYnGs8dUlYcebnXe3Myl0rFWWJAkn42Y11YlfWB1ZXKgw6O/X+eLPKyZ8cbefbudkyrzIvzGz0ognqpgq2MlRkNJrB/BybHUgAqWiugUHtos+wLjPQPoUM0NRdcUEGsp2rEaYg924IeOiYO7cRNO89naBkg38=
    QBITTORRENT__WebUI__Username: AgB/eaVQhfj6vov0LNOLIRKtqcpAF9E4CKb6qj0q7isHqWk0LekunHB79qltj5IxdDvHj+20PFVSmx1CtLCiCrL8tbdZAIy54Ms2PKIN3/BtaZ0fftXDIsBxWB6UvQpVKdDaQ215IztRrLHiIe+6lYndFLAiHHz9az4bKZ967pXMazvvDcF5ItjMQgMk5V9lF5kiOa4y73q+H2zrqKfBjYuX8hHMoNUtvdWuT9GuYotcc2ZULK2zumtUK0yc5zgHb+A1MIn2e6PS5Y89k1MfWmfvtvRiGcWm2X1IlVra32wBCJ90bvHtvtx2KLxrYPHB1BMuC31jMHu6lpg1EU1FzlQ4w4eCi4PjrFcRSpOBe1/fDWVOMixp+WL0NmT4+pGOwmue6ECUK7tknjvm6C/kVLhqiyXtXmuX6xdyBb4XsXXpyKv/h+cxCpSee6tiyVuzeF0Ql4ng0TP3AnMjreqeaHLAt9ECDQdBZrdLs373ejp4v/pALfAjVUaovrOgE9IE3XldqFKVpFe5xJ7EzhIP9Hn4P9Sno60/siBBy/qRW1Bi8T4neyUv7gmgZ1spTJ0YPS9jPrQzgSE/+vZU7T22u31qJenOHWjk3ta3dzc1IWpQxr9eI5XrTGY7+ngqHdmhTRTAIaXgnDtE81oHwhj+9n6d68nFA7V5ECQlxvLwbJ7C/KUQ181FKqkoZit7vTIrZ/DfnmgNxQ==
  template:
    metadata:
      name: qbittorrent-webui
      namespace: private
    type: Opaque
