---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-webui
  namespace: private
spec:
  encryptedData:
    QBITTORRENT__WebUI__Password: AgAooueOK1Z7WULk/Hczo24QNTjtTVGxsX+RwswJbf81EsilPTAq0C0gSLKLmDu0L5gxxqd7RvuT7uQvYUPKGjE5bXsuMg+YZ2MRS7/SAT2IdIL/TciM4b9dUuZngyILVw+s8MWYiBB5QqD+anzqB1hNCSJBHWGuT47pqql5YuNGOE2+MfYYJwjibI0ZZE9BbaZye1P/LqdjXTE7tne82PkIrO33gdEjHB5tMyBhXEl9tS0swayUaBK4sAmwIsTTsYuNGtTDFGN/J9B/ZNHOcAw3J7XIer+MKhkJrKlVgs6z89JdMbGTVZO1fuEXTMLMMVN2fcUp5TnrY7tBl4IbA3DdNrpVWs1rAcldXItyjwVfx+ubLcDaKndDVclumIWItWzmhSdk2sh71C4gb9x5qIVMEePpAVNHCrFl2bcOv5MGWPhPlpn8ZChwUmOlYBMDjG5L/9mo4OGGCWwabZQWDPVQxvzPHTwLHcf3gClUF/zOm9t2Txxn44W7pPa1Q0nr7NbKT7t32XOjj/nTy9SKbWkXCv6/4dKi02dSfqmsXHelW1y78SN4SI9PjvslDaa3txhrEEGnTge8kItLTpTYxppZ62RL6b7/my32AVR8edyQIn77w7ndnTQbo5MtXu3zXb3ap7HePAwoxFJeyg69PGpccx+NaPZ3L0eG7CirPtNLKWC+9dYawcIrAwaP3C/eix6tIW90laRyrYadIHwced66q0n/aA==
    QBITTORRENT__WebUI__Username: AgCdlkGb+pRroBJX6WXNEtvVEDd6hnlhmtGCaJTJsoQgiWLNXYHLoXZTCrqN8SWXDAkdyman3Q9KTbtV229ZKZ5KcXt3rLexAruzFFLgT7cNNoyWc7TKPVlVhI8zP7RJRut7bG/KEaTC3K2Gk6z7UeG1vBiw9sc6zOaZ3WWd+ZS2VMR5O3Ji7MAJGMhUtkNGecFLd4VotySy58mtAWwvfpbjInZDFGHvYLHNB613rPKdV48LEkVXla2dXFLZKOY9MvHPCmE45BbUVSR4oQnEXyjgoFyunWauh7S1WiOdIFz+wZbj2+DqraEmAWzSwlxgHJzOdEspGCy8ggUGM4fb/GrXfGLC2slgd1C/Ul/2hmq8eE9HyYf/Y8AME9/p6b35r1wwWJcWhZ107m6B0I2jCY6pLo8KrCP/NICLJ75kviLUtsYgxINjdPd4OhvRguU9OFUpPMVCFD+3sPjc5wDwaQZgXgisaF7V5EIBeMPDsFBnGn6Af+iWj2+P+4PZH6HRwqYv52EiAW5QvwFHNyBYN1N0iqehUwmONW0hfAi/+qS3GBAA2GAgJxNU+ixPNLbxfjg4xwpka8OurwLKRWpvKlJcUB7821LB/J75B0DvCmnJ6/vG19JI40QVPzbxjG9+3iZl0ULsJBWTFCj7tTYgu33DgE7vew88QcTOULAYN34I8DuTSDn5R9GohoByS4LKHMRy/ANj2w==
  template:
    metadata:
      name: qbittorrent-webui
      namespace: private
    type: Opaque
