---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-webui
  namespace: private
spec:
  encryptedData:
    QBITTORRENT__WebUI__Password: AgB3mKmESZUNuXtuLNkAitrC8uZ3p4In3heRPTyg444ypnq3dVjOjtgjb0DXPPgDXlc11uMDqyAzYU7EX9NJSYHR8y9R4IjsCeOxySKNNL2NT+w7VQu4MOkYzfuHBeVbDY87oNLn3RLIhnyaQnNXTl+FnDV/YApPtLXNQUJb/OW0HHAMPVcYF79o89IYXlcVvWUK4ZZpo4nQvLXQ9TFf4qa8+iVYwBA6xDQqVmXqAzipgLOTFh9W94O5xE1JWooEpSATmRNslaFVQgYd+7BMEWRhUJPlyy4dixo9QFIRnBGgZ6LjX/g9frunG3QFoCvE/2TBw3DJckJEgXd+EQA7NGK8E1VkVXJl9kQUn+P7nWvrZsScF8Tb8vV6dUKYwI+fB3+UOyf32UsK/B+6uoZ57BjhXNh9uaKCle2LBaa1EUtcvQVaHoRlqHyhYUjtWT57UQSNtXnXRTcYvu9C88imgNPwZbLaE8DuwC2j17Gy/bolYp1qx5qxHh8VmuRf3mowioRyWOWLorSO09q0fsmhKGqFOi2SJ2ZKvZfNvsOuC+WzwdOQrvE9f+mbZB4su3h2dsvWHLdZSO2a/WK1PwO79A+zF/aF9uOokaVfvCquTl2r7hzq+lQd2Tv0/x5PIwE2A+/v/HkVaz1/uNeBiJqJSCNj2Al8LABQTEh2TOE8KgkWZrMxsd0CQtIkGJ/pjaSv31qx5U49l37OnWL7NQ6n6L+fICH6Mg==
    QBITTORRENT__WebUI__Username: AgAKkFJ36kuFJUuRGGSOMMwzigvhN2cTJgpVS4ogTtF5RI4Z+ytCh8G1j8D7PerS5rtqG4mIVtgFwruij71yP2cp6qOTN8wwh0KJEtQOrWmFbqL3wiZL7RXpz04TxCu189bxMO+SYPCNYRJJY5mrkrcB790wVOYgqxxSZFtroviJGl/xclZPccTGdF7EXVpmvvfOifAGGK6OdLo0iUj1Fdu6UGSVeu8xU5DwxSZui13/sPghlzzvZOmP4j/u1OAfbXUKghWNn5vzBciqjwdhgcxOOVTSSelpNyoNywIVyP8xeE0y1OSqg4A2xoRC8Ns+698VDvqZw3/G7qXD56pEJSj2nIXIVLzwHxIy0tFfH3DO1rISGEX8ULQQ4h2DrfIj6SQMGdq/TF9fFcS7VCm1RO5RBoMxqQN53mv/kpfPeGYfRwrq417hHSjlaTtmy1WPBP+Hb52T3+Z4Fe0JCdgI2b7OkSxBEGjwdhqQumFQnRAKQXJv2mNXkawQwFZbf4wGqnEM6vI0aFbLNIAFt0Ya8XXgMlXgLAO/J01ZJAMNe8cS0Zah8PAPllwsyTDlb0bsn9YBDhwBmPSuyrKyn/wK9A/yMVqTSSonkXaPPnoyivzgS7rXRPtmvhHnt2T53EA/XD+lV/GmdS9k8pcY0RBgjncSNLOOH8/uVBzPBWuZXNPq5ZB5OErG5k/PNx/hPGCPyOsz4XkPdA==
  template:
    metadata:
      name: qbittorrent-webui
      namespace: private
    type: Opaque
