---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustdesk-key
  namespace: private
spec:
  encryptedData:
    private-key: AgCpGn/kTj7O5IPD2onabMAdCHEpXe1Tlv4JU7+qS8eCb2VlNTZmVqacvt+pT014pYNCgXIg0pfQS152vrSLykrlEHuJY8mt3xodQghB7A1rlnXUkTRiF/wTguQy/NA+L9s42l8G2/0B713YY0VBEywwbaESeA18lUzyuFITupK4nPc8ymmmMZcAkb7HP3h4wYcqvOhm2zErvsqsGOmKA1Fhd4jVvXgpsXQLw/T1p7bjJs6MYtPknZ+lAYtzZBe2DgzNPslpgEItwvVkTUo8UT6F0v7FnqG6mu2q4JLMhp5z5w39pQFiyLOU/9TzLi3063mDPitkOB24Fgm+YSG6UrhK7KshWRm7dqBLGrT0rha7q+4K58URKSDyX2hh+pQF3gFUcx8bxIoN7eEgrvymqRi00wYCThWwwVVn4U4K0SmzslS3EikMe30qMlEV3T47zbtocTw+5yeGgelb6tDCRXR7jcOPgW/j+Sxt9lrG0IA/w9R9/G4dDMcLPU4OnV42Z5lIjh9z8YraY0bFiXjWO1AaMPFLkHNpxyoduJUKwEU1RqqrNB3UfcYr3Ey7NARIRpAh/leE4dUOsmiLsINuybn96et3NmOhEq5h1qE15O5c2uLDw9Yz+E5Dr931nzAXfkr3iRKzAh2jnPAWHu6/hqVVzhtyQLy1sKAKwHNuNY1AICzJEEz4XIaWfURhnkewup7I1mgnTJLurB5gHoNglzbgbip/qqzvhAS/+mU6rilKvXUl4adVlskCz73yaFS27qHJLYtTgp+GVM4b97t9g9oPZV9656odv3lUkywgANLPqW4rYJpWOxlq
    public-key: AgCRSA9QKZMssSrPLh8Bbdj36e9Ewt5H+kJ89a5vZtmWsOy7Z2qUh5MjGWuJreWQkli1cLmbsHFE7ICYYhMFr4kMS6B7r1eZG45nY5kMfYEjB8E6uG7ekxTFn4rLNYuOI+gSEVQw5iiiFW8OLk7IllQOEKKTRSLkzGIQKqMRTblVxbnycSFzFE0SNBQTFmG6E+JK80U6RACEUFrp8c17eCzhMGAbtg68gPx9WB+KJHLQGtre/r/4h7N0oBwl0J+sj9Kdj01BWEVk0Nw7gRZALBJSTrrBHDl7APencMHfLF+HW8VYjib+UAHbl7MpN+Xvq1DYecAppqMHoqM8TVENTSVQWFIXZW+ZT5VItNqoebF5w/Z2M5HhEUi9qdOAftPKKhiVHHtGPiqPSsraxbjGSshrameCZj3BSKYO7MXls4fGsrIRwNgRvB5Tc5ZEUTJnhcC0Rg6QRmsxYD6tcUpL1qUe3Dkl4YoWNJp2iMZjozUjC84S8N603eqflY2aS81m/7mTWaD4b/PaxA5SpSQyWVJ7d4CTudXlouUsh1e9Zm7KdVrBJyLJlb9hUyeQ0LQQTitrlhi3Clhm29tPgPshDImMyleRzWUen0pYPmLiMSW+w7u+D7YeFIr9X48qmEkRr3g47ZEXQs+P+HuTsieP1A0h6efc7XZe3DhhoKAskoH/iIp26bWINbV37mw6XeyO/N/rtXMcTU3DR18oamO5bvl+3T/z8dLJ/FiS3xH1E1CA4lAyWaTe21Xbl/vA+Q==
  template:
    metadata:
      name: rustdesk-key
      namespace: private
    type: Opaque
