---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-git-ssh
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgCBEuhRjjVxM/dVVpXSbmzU4WLu3RX1KDdh8lU6sZCofODZLrUPUsOK6FkfGtDH5sTxc68YshiYuBGb8bS/DgHXhozAbXm5GYeIVwYBR8jvYPtGgCHjpzscSbXvwRKEz67CYFGJ+3uQNs9LW0jf5TKxYAk2btSU/b8mt+AzcnWih9wMlY1pesv19O/Gbju4XgRVE549IwFkhiE+tQs7+grW8ofq0jvtkrx413lxDHzdImEItrZHpLLLWv8Jsiu4KhM1pRsW+GqzxeeWRr/3qqmSLPjSN1YTiS+EN2DhICN4Bpja/Fa+HK9+STGazSGtbpvC69BTmAbGllC4bQ0lGjdZFzcmvhz5YCrK+AFUb7QWJCZicyXRSOCfOpeINDVKDKFQGiRfKWe8TEI1QG182jYItTodgwsYKYhT5p4ahzoOgS7ajyJdAVwnru56wZDOE7ea1BDzGnYCortVR6+EfRFK7YpCeSnV2qkySbGVUv67n2WSepanV2gmSX2tHE+7WslVHvhe47optuh6aCLzCvfGijzhuUJMPwW3HXRnlIxwz/w/zyQUln/fQYUkynrdzrSKHF7T1Sz744hAyoJ1D0txwz8Uf10+dYf7C/5Ajty0uur2PdTGPFJjip0icKKCV8TUHCxWk30UKYFGePcL+ifPU5/o3TBWHqcKzKIJawv9cZVIQdMUG2rRejV4Sb2hAfE8+CfqlYS4usa6MphOtqgvYmcEK+cEezk87vrwpDNv+Oi/DvC/mqFmFmE3PZSGf6WZdeD5ANGRYfJ1Oj/ut7YiUjU8R2Y3y9+aell3aNOunUK8D1qxKo92Hvt9I+C7H9ITcRkJZfq1tn8BjXpb4lOlpxLFdFQdYkrS8EmaIJjaS9KgK77SOp5v5Kaqd6XgQ8AtWPMU+R4IbceUxmkpSX+aRGJsvP2qmegcEKh1cf3qIOTuY135YV/LtL6i1Pq0marczIcdUI/TN9jQQpPurSrHmcWzfDKsSAzpArCEts5GSXuTDQAOT4kwYcqwt6z67Dgdmk7J7x/Md+wI0Hu492/Ldoj1FjbFYf12UKo3//VUVwwaERa19JHyXaH0koNffCdRAZ1lBee91ZGVyT+00rfgoYYNvMkQm+rBR4EfuuIjwWIu9vdu5Iy9fLKvNTKe6GOyG8ksb1srdrffjwVs2xtebfwn/0HMhi/aMRIODmZLHtYqEARXEnfPJcjyEZTtIeIrT23U8Zscol3DoaMnHvqZFPnfh+6MOSXMnfUASfjcCDMm33UKxRKr1FAchcrTC7WwazRugjOUHBB9z1E=
  template:
    metadata:
      name: argocd-image-updater-git-ssh
      namespace: argocd
    type: Opaque
