---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBFr4622yx29Ksf85OU5YemXvnbJPM8bJaZpNlcKdnGY0NfHce6lIXQ5v+RHXanfmPU46lRcnqcrA4qHSivfoF5wXAeBy9SKg4DIvceVUem3slh16hdY1cS1kSDiTA5BuSXig+SS7xyPP73d3boByoGCyx3kPTuan/qy4xv9Azf4KFx8ad5r0qT4HrKW8PAQP5wInM6FLp+nEgmowUqiBQzYc2V1DuBrnDAIRW5WgScw+bBgAd+sCXJ12/ZsnqWSgVhf38DonZV9h63CuyaBC2md9BxloIuaKuSmFk7A5RF5kUWC3eux8rLQApVfTx+9LONIGUTeuHxxLFOVpJUOlhwKa3ttKzQ6qigYwe1O91A2R63nvnwEGmX7DOjQwm6c0yisW3eCqDVsnFq/2sr+bMR+YO29U1SEvG3saYlR4iWVPTbLDKO4XyBfJh+iz10EKLsCsRspx7Bm3Wap7sSdjLQeyuIpvy2GV0QSbz4QC3e/Q+kkLD/8oYYVCJVWl+iRPEAPesjH3Yz3NpKD92RQ5ymdypx/+kXWCrE6fcOVIvOghZavqVbswMTBmLXBa7NG2wBDcHMT+H8lZ0YlIwKX+vbwLIiz6s1g2bKRE9mvNMfeQK7AiCv0ItiZXBjZ8zd1UtAKIUVJIzarNnYunafKEePyDuPND6gZSSr4DuHpzU65PN/+uQtgzRr3wmo72tALMIlZZpV1aTP1PnNOhq1Lnuf/GiW5UZ+o0eTnHHa/RUjkRu81XAn+b/A+1OO7y/pWLVKhvm6AyE+jisuSZAg+aOq1L6p13z9uLn2znbCThNX4mq2x1snxoy4ihxe2awHbc9+AawnLE4mqP10/csdCU3wgk12zKpVCVpvtTI710extXDxASGnStcdqxn46VizByDLbrXp6RtQwQEdCpax+mwp8SIE0AznA1hW20+SsOSJNV7H0Q==
  template:
    metadata:
      name: ghcr-credentials
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
