controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/doezer/questarr
          tag: "1.3.0"
    type: deployment

persistence:
  config:
    existingClaim: questarr-data-lh

service:
  main:
    controller: main
    ports:
      http:
        port: 5000
