apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 1.2.2
    helm:
      valueFiles:
      - $values/apps/infra/argocd-image-updater/values.yaml
  - repoURL: https://github.com/mysweetpea/homelab-k8s.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
