apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: homelab-image-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: git
    gitConfig:
      repository: https://github.com/mysweetpea/homelab-k8s.git
      branch: main
  applicationRefs:
  - namePattern: n8n
    images:
    - alias: n8n
      imageName: n8nio/n8n
      commonUpdateSettings:
        updateStrategy: semver
          allowTags: "regexp:^2\\.26\\.\d+$"
      manifestTargets:
        helm:
          tag: controllers.main.containers.main.image.tag
  - namePattern: immich
    images:
    - alias: immich
      imageName: ghcr.io/immich-app/immich-server
      commonUpdateSettings:
        updateStrategy: semver
        allowTags: "regexp:^v\\d+\\.\\d+\\.\\d+$"
      manifestTargets:
        helm:
          tag: controllers.main.containers.main.image.tag
  - namePattern: homepage
    images:
    - alias: homepage
      imageName: ghcr.io/gethomepage/homepage
      commonUpdateSettings:
        updateStrategy: semver
        allowTags: "regexp:^v\\d+\\.\\d+\\.\\d+$"
      manifestTargets:
        helm:
          tag: controllers.main.containers.main.image.tag
  - namePattern: jellyfin
    images:
    - alias: jellyfin
      imageName: jellyfin/jellyfin
      commonUpdateSettings:
        updateStrategy: semver
        allowTags: "regexp:^\\d+\\.\\d+\\.\\d+$"
      manifestTargets:
        helm:
          tag: controllers.main.containers.main.image.tag
