config:
  argocd:
    serverAddress: argocd-server.argocd.svc.cluster.local
    insecure: true
  log:
    level: info
  registries:
    - name: GHCR
      prefix: ghcr.io
      api_url: https://ghcr.io
      credentials: pullsecret:argocd/ghcr-credentials
extraArgs:
  - --registries-conf-path
  - /app/config/registries.conf
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
