controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/hotio/qbittorrent
          tag: latest
    type: deployment
service:
  main:
    controller: main
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: "192.168.20.225"
    allocateLoadBalancerNodePorts: false
    ports:
      http:
        port: 8080
