---
authentik:
  image:
    repository: ghcr.io/goauthentik/server
    tag: "2026.5.2"
  secret_key: "ysoC/gBZLhn8aQeJE+Drch32mNPgQuDxEygwYqecPz+D9MKRRh7UtPGTZ/5YUVrMG9E="
  postgresql:
    enabled: true
    auth:
      username: authentik
      database: authentik
      password: "authentik2026!"
    volumePermissions:
      enabled: true
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 8Gi
  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: false
  server:
    ingress:
      enabled: false
    metrics:
      enabled: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
  worker:
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
