---
authentik:
  image:
    repository: ghcr.io/goauthentik/server
    tag: "2026.5.2"
  secret_key: ""
  postgresql:
    enabled: true
    host: "10.43.85.107"
    port: 5432
    name: authentik
    user: authentik
    password: "authentik2026!"
    sslmode: disable
  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: false
  server:
    ingress:
      enabled: false
    metrics:
      enabled: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
  worker:
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
