apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: netdata
      repoURL: https://netdata.github.io/helmchart/
      targetRevision: latest
      helm:
        valueFiles:
          - $values/apps/monitoring/netdata/values.yaml
    - repoURL: https://github.com/mysweetpea/homelab-k8s.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
