parent:
  persistence:
    enabled: true
    storageclass: longhorn
    size: 5Gi
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

child:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.20.229
  port: 19999
