apiVersion: batch/v1
kind: Job
metadata:
  name: mas-syn2mas
  namespace: dmz
  labels:
    app.kubernetes.io/name: mas
    app.kubernetes.io/part-of: homelab
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mas
        app.kubernetes.io/part-of: homelab
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
        - name: syn2mas
          image: ghcr.io/element-hq/matrix-authentication-service@sha256:e82b2e4a5f9c7ca74096743349160795f5b5a792556fb85c6b5166a9180a5985
          args:
            - syn2mas
            - migrate
            - --config
            - /migrate/mas-config.yaml
            - --synapse-config
            - /migrate/homeserver.yaml
            - --synapse-config
            - /migrate/secrets.yaml
          env:
            - name: MAS_CONFIG
              value: /migrate/mas-config.yaml
          volumeMounts:
            - name: migrate
              mountPath: /migrate
            - name: secrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: migrate
          secret:
            secretName: mas-syn2mas-config
        - name: secrets
          secret:
            secretName: mas-secrets
            defaultMode: 0440
