---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-postgresql
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: private
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: "18.x"
    helm:
      valuesObject:
        image:
          repository: tensorchord/cloudnative-pgvecto.rs
          tag: "ubi8-17.4-v0.2.0"
        auth:
          username: immich
          database: immich
          password: "HomelabPostgres2026!"
        primary:
          persistence:
            enabled: true
            storageClass: longhorn
            size: 8Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
