---
apiVersion: v1
kind: ConfigMap
metadata:
  name: affine-config
  namespace: dmz
data:
  config.json: |
    {
      "auth": {
        "allowSignup": false
      },
      "flags": {
        "allowGuestDemoWorkspace": false
      }
    }
