apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIUNf7e1dn+BGtbEy3HMCHHHt+FKPIwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAwwSYXV0aC5teXN3ZWV0cGVhLmNjMB4XDTI2MDcyMDIzNDYx
    NFoXDTM2MDcxNzIzNDYxNFowHTEbMBkGA1UEAwwSYXV0aC5teXN3ZWV0cGVhLmNj
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtJRLaxHgGh+xA5sz7K/s
    0LRt57BCKVlPnTB0UfzYV1VrqBCH83ABExkOJozYIxbWr4d+MY8loQx71IadB2Wu
    SmloptLXXpu77ZAtwN9Flu+ALCKTH3kXzXDc5isDnsM7DhKZb04TlhBkqYHwl6BJ
    Gl5+koKZoQrJuz8jsfZJ4Oiu2gJRkIQrvJfGuIUTT+p4zH/S0oB4Q0GLwqbgs33n
    DswAan05IZlsLXwYOIvLgVAJOqo97cuAGbpHdJkxShLpDtqQ/krhjSZrBlIRQDR0
    3/q2RJ3/8OFnbc3GZzqYfjzL3IjlBcVpARyXjynZ5NMWU0C8d3OPMptgldNHiO7T
    yQIDAQABo4GDMIGAMB0GA1UdDgQWBBRpl5lm4xfWQH6mmQG4NryVP58wgzAfBgNV
    HSMEGDAWgBRpl5lm4xfWQH6mmQG4NryVP58wgzAdBgNVHREEFjAUghJhdXRoLm15
    c3dlZXRwZWEuY2MwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAqQwDQYJ
    KoZIhvcNAQELBQADggEBAJVil8ZkjfLyAcI+JGwbhBk8JYjUGvQq+CMitySJ0XG8
    +djKNQSq2ahDcCybI+jRTDo3+/R5bvZgPguqS5wp7IGi7eRJ9QBZNVNAGx/MWzVd
    7TYnvUB0mgVBS5SZFyhfH2OnVwGlMU9zY45Dizdgnz04VpA1msnGL5flJzVjbFmS
    m4nJZ1wDEuEfyGOz2+Zv8A/+bJBP4wWGql8jwETkonlZrvHZMM/Onm+69LeuNyJ/
    X0/gTknVh50Wn9r3UiZ96PV053m1ujuw44R0c89zW7zAjkeGQf034ROAcMtfBQIc
    uPyoNSiuVpsfTrjONOqe+I3No9c8IdQCfGP+IaSR8TE=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ca.crt":"-----BEGIN CERTIFICATE-----\nMIIDTDCCAjSgAwIBAgIUNf7e1dn+BGtbEy3HMCHHHt+FKPIwDQYJKoZIhvcNAQEL\nBQAwHTEbMBkGA1UEAwwSYXV0aC5teXN3ZWV0cGVhLmNjMB4XDTI2MDcyMDIzNDYx\nNFoXDTM2MDcxNzIzNDYxNFowHTEbMBkGA1UEAwwSYXV0aC5teXN3ZWV0cGVhLmNj\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtJRLaxHgGh+xA5sz7K/s\n0LRt57BCKVlPnTB0UfzYV1VrqBCH83ABExkOJozYIxbWr4d+MY8loQx71IadB2Wu\nSmloptLXXpu77ZAtwN9Flu+ALCKTH3kXzXDc5isDnsM7DhKZb04TlhBkqYHwl6BJ\nGl5+koKZoQrJuz8jsfZJ4Oiu2gJRkIQrvJfGuIUTT+p4zH/S0oB4Q0GLwqbgs33n\nDswAan05IZlsLXwYOIvLgVAJOqo97cuAGbpHdJkxShLpDtqQ/krhjSZrBlIRQDR0\n3/q2RJ3/8OFnbc3GZzqYfjzL3IjlBcVpARyXjynZ5NMWU0C8d3OPMptgldNHiO7T\nyQIDAQABo4GDMIGAMB0GA1UdDgQWBBRpl5lm4xfWQH6mmQG4NryVP58wgzAfBgNV\nHSMEGDAWgBRpl5lm4xfWQH6mmQG4NryVP58wgzAdBgNVHREEFjAUghJhdXRoLm15\nc3dlZXRwZWEuY2MwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAqQwDQYJ\nKoZIhvcNAQELBQADggEBAJVil8ZkjfLyAcI+JGwbhBk8JYjUGvQq+CMitySJ0XG8\n+djKNQSq2ahDcCybI+jRTDo3+/R5bvZgPguqS5wp7IGi7eRJ9QBZNVNAGx/MWzVd\n7TYnvUB0mgVBS5SZFyhfH2OnVwGlMU9zY45Dizdgnz04VpA1msnGL5flJzVjbFmS\nm4nJZ1wDEuEfyGOz2+Zv8A/+bJBP4wWGql8jwETkonlZrvHZMM/Onm+69LeuNyJ/\nX0/gTknVh50Wn9r3UiZ96PV053m1ujuw44R0c89zW7zAjkeGQf034ROAcMtfBQIc\nuPyoNSiuVpsfTrjONOqe+I3No9c8IdQCfGP+IaSR8TE=\n-----END CERTIFICATE-----\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"authentik-ca-cert","namespace":"dmz"}}
  creationTimestamp: "2026-07-20T22:33:01Z"
  name: authentik-ca-cert
  namespace: dmz
  resourceVersion: "15088074"
  uid: 28c3674d-44b8-4919-91e5-3e5e85fa7282
