apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustdesk
  namespace: argocd
spec:
  destination:
    namespace: private
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: rustdesk-server
      repoURL: https://sachajw.github.io/k8s-helm-rustdesk
      targetRevision: 1.0.1
      helm:
        valueFiles:
          - $values/apps/private/rustdesk/values.yaml
    - repoURL: https://github.com/mysweetpea/homelab-k8s.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
