apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk-hbbr
  namespace: private
  labels:
    app: rustdesk-hbbr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustdesk-hbbr
  template:
    metadata:
      labels:
        app: rustdesk-hbbr
    spec:
      containers:
      - name: hbbr
        image: rustdesk/rustdesk-server:latest
        command: ["hbbr"]
        ports:
        - containerPort: 21117
          protocol: TCP
        - containerPort: 21119
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rustdesk-hbbr
  namespace: private
  annotations:
    metallb.universe.tf/allow-shared-ip: "rustdesk"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.20.216
  allocateLoadBalancerNodePorts: false
  selector:
    app: rustdesk-hbbr
  ports:
  - name: relay
    port: 21117
    targetPort: 21117
    protocol: TCP
  - name: web-client
    port: 21119
    targetPort: 21119
    protocol: TCP
