controllers:
  hbbs:
    type: deployment
    containers:
      main:
        image:
          repository: rustdesk/rustdesk-server
          tag: "latest"
          pullPolicy: IfNotPresent
        command:
        - hbbs
        - -r
        - 192.168.20.216:21117

  hbbr:
    type: deployment
    containers:
      main:
        image:
          repository: rustdesk/rustdesk-server
          tag: "latest"
          pullPolicy: IfNotPresent
        command:
        - hbbr

service:
  hbbs:
    controller: hbbs
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.20.216
      metallb.universe.tf/allow-shared-ip: "rustdesk"
    allocateLoadBalancerNodePorts: false
    ports:
      nat-test:
        port: 21115
        targetPort: 21115
      id-reg:
        port: 21116
        targetPort: 21116
        protocol: TCP
      id-reg-udp:
        port: 21116
        targetPort: 21116
        protocol: UDP
      websocket:
        port: 21118
        targetPort: 21118

  hbbr:
    controller: hbbr
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: "rustdesk"
    allocateLoadBalancerNodePorts: false
    ports:
      relay:
        port: 21117
        targetPort: 21117
      websocket:
        port: 21119
        targetPort: 21119

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: longhorn
    globalMounts:
    - path: /root
