replicaCount: 1

image:
  repository: rustdesk/rustdesk-server
  pullPolicy: IfNotPresent
  tag: "latest"

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 1Gi
  existingClaim: rustdesk-data-lh

hbbs:
  service:
    type: LoadBalancer
  resources: {}

hbbr:
  service:
    type: LoadBalancer
  resources: {}

loadBalancer:
  enabled: true
  annotations: {}

ingress:
  enabled: false

bitwarden:
  enabled: false

keyExtraction:
  enabled: true
