image:
  tag: 31.0.2
nextcloud:
  host: nextcloud.mysweetpea.duckdns.org
persistence:
  enabled: true
  existingClaim: nextcloud-nextcloud-lh
postgresql:
  enabled: false
service:
  port: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.20.215
  loadBalancerIP: 192.168.20.215
  allocateLoadBalancerNodePorts: false

externalDatabase:
  enabled: true
  type: postgresql
  host: postgresql.private.svc.cluster.local
  database: nextcloud
  user: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-db-creds
    usernameKey: username
    passwordKey: password

nextcloud:
  host: nextcloud.mysweetpea.duckdns.org
  username: admin
  password: H1vqWaiNyd
  trustedDomains:
    - nextcloud.mysweetpea.duckdns.org
    - 192.168.20.215
    - nextcloud.private.svc.cluster.local

mariadb:
  enabled: false
livenessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5
readinessProbe:
  enabled: true
  initialDelaySeconds: 180
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5
