image:
  tag: 31.0.2
nextcloud:
  host: nextcloud.mysweetpea.duckdns.org
persistence:
  enabled: true
  existingClaim: nextcloud-nextcloud-lh
postgresql:
  enabled: false
service:
  port: 8080
  type: LoadBalancer
