apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.8.2
      helm:
        valueFiles:
          - $values/apps/monitoring/grafana/values.yaml
    - repoURL: https://github.com/mysweetpea/homelab-k8s.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
