---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: affine-smtp
  namespace: dmz
spec:
  encryptedData:
    smtp-password: AgCUk1dmzkGRvQpoGP8UIrBYYsl8X55RYXgQ04eESaXU6EnIcJhP3u3cSg8I/hl++/hZhG7RgRpayjWybXxldiYoyuJp9h/vOP5R3hW5o4uj4p/8gG6qgLeLZpS7/ZvL6kiLk+XI9KYyxUlrFMq9leapu+clJRaFDaEzRh+qD157PfBSHlKR3CpYsySCUVHUxo1EOxZzDdp6QMuvrZmx40mPfH4mCgg/Fkew4N1+aFnLEKH/Kb4tl4HWkosl9d1eb9xMbPyHLWRtkQ5gXodQ5tgU4mK6/US8XTJs+TDim1haPGDAfnXd+v0+pkTaDwCBGXZ5v5LVZLmO4NJ/Yf+QAYGbnezWoJMITnOcW3ouYGkAnOUp3O+AxnlrXF5WAPory+5RZLADugyFgxw3/GMKZQ0j5RHmsH59GVJ7kg9v75OuZ9Oi5n52DDu7bGpW+9uLvHjA+/f7C5Ue0YMWBmVkpiPAc8qYgP+s1Zt09KIEEbGW1L9SyVu6jjCvTP1NSNJNv4eBaYnJlF85TywaVfudu+LC6QHKdxTKksKvzlGMgq9uufbKkxZzyswpvAxgOJvv8CE+TUqjXBEoL+YgC7RNn+WMTsO9WF+FDDgOcHriOVR6MgMg1qpxwimNMdmRJFA62E0cmxVa5Tv7tOctgkcWFuq+mqxVhqTfLISSNlzDiZHrHQABRVRSs6mOhQx0Ayx0JOl1cfUqcsXPCzIW44jBW2okHlagxWyrXS6FCT8iyzO1SDq65sM=
    smtp-user: AgChfO/HLMADIFlwtoqXCYs54IjoCh+U248TyyKH5q6Q3VTrK7v7qZIs8JRm+z6Iw0lhcYdWCIkTmBfxgmPfhoEXs66wywNcGfhKJkTzsuBrSud93I3EOjt964eFm59mLzGUZt/G4QUiNe+su06l5QOnL710jnc4YWNeBNZceEaHWvICIFhnmujqRkNGNhVBUMdI9npoOw9KTuY1AB45DjkWzJHDdXwLOPUkfXK7sNF2TOo+2ydU4xev/7zn6+8T4tCLcEP+wKbumC/+RdmlnAPADF6ggq7rd1SVTaue921CwR0s6C+inGXWjMyW5ZODfSGcRv/tf/1KsfqBpvfX565n8fT3oK9+93EVYDd5/6WhMlQ4ErF/CkhZqRG5baOqsfHONPnbwHC9tnHxgOoXNktP/x40J3uQKEXQHg3nNenNuKa84l73OP+8S+96T2XtmI6DjtGiCe2LS5//V99JI08YxyyXt35aMsPWuTDK+yh0osgQ7Zxz+JA3uNsnsLNRxWZvstWiEvTlFihsVgWNmozjyael+vH0Sr3pdKGPDNJeaRaXghdeVaOHKCnzW8aE+jmUOl238RVsC5xIwHv5xvoargfGW381rxRxVM6TlQsqFgdDqlpbYZbE/7uFGe7yWlQKFJde2UnZyGorAdAVJe0MBRPC1pbCrbyir+Da1npcuI7teED60MzLfiW8HZYvRwhsIrM7Vzs=
  template:
    metadata:
      name: affine-smtp
      namespace: dmz
    type: Opaque
