---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret
  namespace: dmz
spec:
  encryptedData:
    secret_key: AgCsEO/tA1mCd+/oEp4jdXdPz+xYU2G2W/lhzKQW8XxM+SRTZoH0vF4qiwZCKkdly9qMZYqq4wb+F0dnL0378zQ99u3CLF314MAx94ZP6Jb+IepM/DSf/TZh7pFKcezKpsttQOhqQ5c1IdQf26jmQONjymdcAD4+GFX0XF7j1MNoaiAeQyLl9lvchTfSR6Q4abP1a9xaR+G5KEmFeRErFZbQyTVVJrFN/KEu+Sg55JKJ5QpHKgS4WQNRxftqH/YT5s1Q1jy3y2fON9tNj6SDNFyApj7ufvGVvNmHlxCoRDKcpyHi6QqYeJqxFsMO4/VJT6FNmCfCsSWsqvPf+SFae7k2Zr2cLwXiOCz7amxsPzfgjJ3xgc3IpIJnRDLXbGaZIXADWaOUnQDjvFEpdxmFaZxQgYZdfEJsVNnmqqjAFeNpxg+RyUWkyrfEcMzCQHep3y2mWOMG8PMXOFoUQfoI3zsnKsORJUt1lyBEQZKZwOhblEr7kFHvh8O6ldDcekqNuBM41f050ynuQEuk9FEy9zKWvfjQkX92VyBEou7LdK9s5F28e4hf1EKJX4FYdRVCxUDt6gzqGmT6mrMrmWZbOmfjjzS+VUZPT1exyP6rfAhQxi7qQ6kVV82wtvK2gBsuXGIdIo2IWptaNHuK0Q8hQnyihuyATRKhAtJ2lFXuPK2xeIQjzEi7a20ntG+UaDMJWejzumCNaPOMV8WS5csUHMEHFNF97s5CykLju33X0D7n7HryL5z8a0BaXNJyb/YjB71RSWqrLALtYOcxNuGnuaGZm3XGZw==
  template:
    metadata:
      name: authentik-secret
      namespace: dmz
    type: Opaque
