---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql
  namespace: dmz
spec:
  encryptedData:
    password: AgAcu1pQx6Nd81AEBxoeKBISeIJYuC1/ofTwpNQP5sz1LA/+0nFxtKaydvw4Ry9S8wgDnwkDaB8xl7fyrXKp2Gpaou529dUfTpWwUex0luQtALdRnszmVblC2KK67+1xfhFwhrA4PLd6R9g/fTKMP17NyNoJjH4rkvOhWja9HFRAOQU2YaTsR5DolX6/WPSjUhozD0W5llfGPjo2ABvXmWCS++ndRbqYVjs9NLtO79/VVVyiK+YUJQ9fTsidCllC+Emdc3FtJh2g0BTR4Zg3qI2CpdsvDtkmR3ZhQQti1PKUSJWnPytdn4+RSLgdmcXeedy4kH5gP2qQcAzcMS5GyBYt0NA2OaV0seh1PFFN0/pohPDqE4eOm/6P+EHl1QI/6oKHhjm/MOPP1tLY/kfffEnnUs+wcxLXHFAvbKyvjxxi35JZOZT25SVabAynB9kZtFIKVPPoQflEvkh5dhyj7m6llmk5Xbuo/Cn3EXgmtjeU4/lwRIcqNotG7o6QSLsA2BKY1VvQjZ/PUbmneinTjXWhF8Pj40Oxo39LyUnrUqgsw+Ss988UMEPkvEYoEaF1zjyySzKZUgBTpMnYFdyiB8G7se64AchwFSRo+HmqF9SJ6UJrucdmqfWJmzUgxRZxoK1Xx7paXqWuzFwxxfgEBhMApzPfqG0kwZlVSa1QSTGfCftDb+/liC1I4d/vpynCBkhTZ9l4JkGklwM2+K12nstc9Bvfq+o0UqY=
    postgres-password: AgBEuqAK4K/YOSwy4hesmfzSbsrJU1skC5TMjDGjGKbhMTQYYRhbuZdjslMsqXpB+uFExoMRBp98Nq+npQc3wkZcpueum02wa57qBddXWljM5ago806OYSFua09zaBvXjjMtXjn6fIepzxdnog4KOQ5pbElZMbdcCqKz+IVbFyLT2fOsxDcp9nZMu83Cf6MeoOBqKfV+SuCtacgeRKu2twfgZ0GolC5dzw/dqFCmmt5Rtoq5BK8mZBsInVeGiPvZ9VnXCHROhkQMQwUgI5N8CnKLtwPx8hul0ArveiDfa/C2bHjDvNuBMdCbhXYkZCECkdctQqvHtBt80SU2yDMs+HcYKF2h137IxA04JzixBIqw5iKYhXfgfK+Gnm18jXJyRKEP0F7bf47uWY7RvfCKyS9xaUX84fYxqJ4MwgE4FqZ/+Nawq15dtKrc5w2wPW+l0hwBSjDYc7UIh2q7k4GWXMlSlrHP7rQtXzpbO3tey7A+ygczk27cw4FoBnMBYOPrixbxAnzYD3S0O40z7GZGBjK5ITRVyiNIUBrFosGamF92T/RrzqxpYu/tEkYHBdToH7MNaPAfIMHec0r8YmxZZN4AIuKRcDMxJb30qhzQUaK8BYsbZ0JGqbN3m1bII2BCvYJdrMrQicvdDe1TQm3sjca+ENvN35tVbIoGtUp6G7ihJOPOUea4sXUsv3rVPpzF+xe2tv1bgDCXaEO/QTX1JJpi3ASW3BA/oQQ=
  template:
    metadata:
      name: authentik-postgresql
      namespace: dmz
    type: Opaque
