---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql
  namespace: dmz
spec:
  encryptedData:
    password: AgCEQEIxv3GBca6vh2gu678cUvcLH67x16VDrMdbQIW9vvKoB7Kc0NVpjA5tWXKLDsWZQITRXpbIZxKBrlbIGsfc+DDL7B30IUqDsh4c0kL1j/poQQ093suQBiz2N6mIPCCHTZ4mGQAaT9ZVC0NKXBkuyFxo6Nvshqwy8yN0UKKz/Djw/qw8kIxFEZbIk6l4aT6rzHONGKX1ce7D1+qX3TC+b8WgD41WJ7COhYHzjVAlC+lig0dgFjy9irjQ02wCPUqM70CbQJ1k2WZW26ALWT2AKXJEQ1Lj4lEo0mgSxa5KUMs05saP51tlnIlx6LZl3AovvKpqZn6lUNrZSkMKKHhvLnAbH3OQyz77Z19j9+m/Ow581Ur7xIooMNH4u9cQAqr2iXFSkZmqRApte688eH6uo61YD8FRQI5w65CEJMJqYF4mPbnukV0zENey9Y6HDFCKk1LkAD+4rA+v6pSHoPhA7TAvJ1RCHvnpiX/99pqcGey+B177OXNhKX4eRtnI2OiCOVJ/nL7A72lrzTAzgQ6CLkUDVBTjQ3LCckqLS2ewZkZAqrHXfH5zLdfHCvgGgmE83zyRpTc7uh6R8IIsDAqhqcHUBN42rOLWRzPP+4NWePy9mz/p+FoFYYf0LlYWdr94CuSkBDiYtetVsXPjBxS0IGlDYs741AEXqvfbrvowudQj5U5i5pC1ZDGaqup4yid3CO+IkQ+F3RxGDPHiZw==
    postgres-password: AgCsq5MpQMg49o9xWgQl91qoy+VN5mg9d7CdNVUJTeNkrs3YBIa5q6LzcR8K1W13JO0kHzKpsrdsOANsc2yZDXp1z1mmHkMZU4i3K2H3ofDzdHiMjEXVYvtpbye9PfPLtFIDKtDrM4E55fVywovJvh5eE5V6TJCIJp7gRxvyQyevFBjNyjIIfzS9ZoJ+wcmgp7rxTsZxcHk/83ir4rPXPhiloSjYOdDKqHxEvhcMaqQ70p7mM3DCRa2M8/tLkJj6QwdiapMQng6xvwMyhow5xv1j2ktIL2u6yst8hVQS9hRdM4RaHRKhHo+PPKybHK+eaq+h7NyLSel9r5Yqtjcj4HiA8TnpRWclKr9EmhPGUrf84l4T5f3+b5em1o66LSBAXRUH8VR8AEJDOQ10s4ikjKVM40AKEHe9me6j4yTYnSEoCyEXMrGdxkZuTe9Tw57X/ssTIxKUS4n4lT3UBl+4IuYrL68K9VZxKnXZ66D3c5PrBh7LJJNKg/B1GYgbThgZfi+/9/X9BfKFYgnza6UWwuuDDG7lbQY/0KpumeNgE/lhog1PMRfl3aUm+WKif+VDBK3vxk9x/rR6pnv0MMlszsTs0Msqcmt+36T7mgEu9y5Rp64LJGN0RaU7g4aKnsOYOBrSgP8OEm/51NCFpztoWEUBJPT/cLrp3rse1HAPIKsa6arr0LwCrvf2wUT1RMH+PCig9L2ugI6dcX9V
  template:
    metadata:
      name: authentik-postgresql
      namespace: dmz
    type: Opaque
