---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql
  namespace: dmz
spec:
  encryptedData:
    password: AgCk9CEPaB1XlSMGz8tWJeNOsLeIR53J3m6TxDzs/hJErPb2CqtTIxMVaibTRLRF75ImdKsh/TITrYfm1Z0qz0suNXoEJm4jifI1fpbAakYzcgnSxfhW5WXV1WjkANJwdsFqfFvY8M7NeYd/XANdvKATbJWprLPwJB0zxrQktJo+qylNh13GFIRSgPUX7KC1v8XpsaP/nYCgm6HJWkq2x5oIIRn5oIU5Yk07I39I/99qG98+DA4y5LE+Fngw2rfWiGvaHHgPG6nETxA46/zTI7pgMP0hETBnObr0XmtbdkCE/npfINpyxlLtNjk+Na5OrhbtwI/rhV5+bVmwkPk4bwJPKvwAtFigQ77uGYdc+g/zMnKevKK31E3YusjQYKPSr9qH8FYWH5LIie8GlrrfsEppsJ644j6GdB09OJzlHvFIWVdJKkGSOTVCmoHzsQ3SJGg9+xvQJnXS7Xtoc55H9bWm+oCiqfMQJkkj7lut+NoemH2Di8d7eo7BCnM8LCWgHZJXCnlx3lClU6mE2k3uNVaMiLyaWocadcybI3Ws4CxGIlHxRNmKhZoDLqgED7JBklAVYt6rZTw5yD2vr+iNXRjXCSjNc4HXxpRC2/9K4a3lwzgZE4pwD8Mzuieehc85Tk8hBs9vaVUfPwV46RBBJrtvAOrvu/KKqOvH/8n2boX/TGYIXf++L6HbUhRVDOAQn1ZFtfSMimTUJRJ4pYbEmHcZ26FFD0gOZdY=
    postgres-password: AgBDQBHRtdEbkyWsW9cAheyTuTQXkjeKQTx7a9O50xXn++7r/i04QNgP9DH+g0BQqjHr1AeaqRn7T7tX9jSDpi85tE5C4PPlPOzz66SU2ciHCLVOn7jDxqA729+Q+YcTu3u9dunNOFfiU7qiOLKhA4LACtsJ/15L/9eEzzAdluuRBhkadcBqSMGAmE2G/wjzRl8y1ShWsDKyWL+IyZ5FgTcGTbelbDEvkyv40mLQe1sZjBxJ9361fw33Fij9BOnBZCJWlQuzgGU+bNqlrAda0dYnUJc3qfDBFpJBDrH366Qrj6nTdUtzY/G2e/S43spnObI/Rja/xaBCQyj8fh/rVHTYe1GPjciju8Fs/GOt2U3HXIxHQfkNemHwmi6SGE+zK+gdZknQzUZPY53yCPmCvInnjg2Md3ms+etbh7byTNs8+NGJeReXlYbjhQ9CyiyaR4d0GWLp4kWtzIw2pHip6iiqEvNG0KDZ8/eGii/xieBY+dgLn8FD8QUFX7Nryp8LicImLAxSz5HQgZSit05AkCepO2GghFj6tY2MY8PE7rriCXRXg5VGJE8SXE/jfGeQp9vEV++WdsIglq1mymIW0/69E2OvnN8P673hhDmbt1hoGhItz0+ZmRg60lOeCJpPj+jAo3A7CTCoZ/v3CcCBtx3MfdIVccbW3Uo9bZmvViaijPuaLXeD4oObyXWZ7wjf4xhjIoAuudDfAZ0t
  template:
    metadata:
      name: authentik-postgresql
      namespace: dmz
    type: Opaque
