---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: dmz
spec:
  encryptedData:
    secret-key: AgCmZTomDP2qxBZYL6WCMq/TPmTghopW8XKpWddL8Kqx06Rt5mmjFkQJ0RAZU087pGR008eoZhDCfBcpoawbYX75janmWbk62DRs2OfNDAYQ7xq1WMQXE5gSQo8ItLUC4juuGZO0tQ0oYqXfUZ+x2a55yWMNE/IS3Qf1ev+SddOZy3WV4B9V6peszF6XpO6gcD7rxjg/UEN8NwZsfOWWLq6Bb87h/cCqbASnuIrED6sQYlNBjClK70EFaMhZMVY6tJzg8pR3O3r3bPCRkl81i3PhBD0qGP8q4HOV0zJSu8B0xQsOof8lKPBqra1ukmQbIv98Ui+bEZfhZE7GTLVPREoz/fS0WUb2GSYbgzsHAy57m2YPvnVR+wfgXhfmi21rneQci7j/anOXS42wOLRFLgQV5B08hNt7L7pEXJAPhSoUPZBa6yjVpzgNqyXdN5G3HWYGOLnzRPsEcHIM1c9x18sj/zG02HqeejaClX0T6EECvRjz14lcFRtLuQx8IzF2X7WUgqVe0lA3Pi17cUWhsJOUUOuQ+wbYl/9fUCs5sGl2xdu1tRt2cyOuyupWZLvIdL5rJw0QL/IIhZZj21j0Ur2pvmsBRpeiDWnMnW1WQY/oP9IqGcHdAa9WC82sDOXCvm6r4EonBWxZ7yHwBA0Uyw3zZ+46RSuPwZ8O8yl222tgcZkknE10iLcrKgJHbKwLD8Ye5wUo7ZPAWOFTbxqsTo2FlCWujVvJwOxRE2oQj8/A/c2nR6GduUrRYqmqKN/661f/EAD2tTr05/aKKP76OHLk33fNhg==
  template:
    metadata:
      name: authentik-secret-key
      namespace: dmz
    type: Opaque
