---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-rtc-livekit
  namespace: dmz
spec:
  encryptedData:
    LIVEKIT_KEY: AgBDtLmVTrHAlKcdqP1co5UAj1yhJh11TOyUr5HSLVx0xYwvuwQvOgGumROPD21P7P701nnD9WgPpfqFAyAgDWV3qQP2oo0zpPiCdjCrp13hIZxYOajT1uDtmLKBkJInfnJHqALZsZGDZ2j/RoCi6pwVXE46NW9rVzxn6ZJk9jKOx5UPNTpGeQ1k31WFJetoI5A2HnQsNq4LfLRNzWE68KZBvi81oyA++HqRwBCMYGZ1VDVdYV1g04JUFI1PKk9PA4rwRBwlY31fvRrjtGei2DZ6AZHoyYcCvNNybgwbvWXf1xhCZpwnqMoHMGrD9PdcOxav02aNWECXKfR4cqoAmYChmoNTg3Xu4IMPdXMES6E2I94ODxSlfPzJF91JYKn5ke1podqDcE5iUJ9BB6ZGZ7J7vCF8SXCJk31qQ37NhyCwrzK0xvPUzB9q7xT0uo4nJTfeb22AEf8gkETJwQXEQ08hvNr0wa2wPR+So9t/mpA6kdIaSf3rHueOqOhkwO7XhX0tdco/1RCXSFoGZXif3WNpblUUMOyeTU+VXIlbie/h/cPRvl1X4aasjf5Q2J5KE0ZzI05Lvw4LDoXWNB1LsUicBSrj45BU8adlK9ys9p2jDjSzBAsgkUYo4TUlykaoDBfbwv6KdoH6pzSLEt+I9LeioM1eHsu0svLZfTf9QCavDReuDDRtG3nr7ppyR2CkTm8ngKK0dWHQWYgLQX+B2KtqdG83ZszL2GOPVs97x4jkUvjcFCBGnEirM52GKaB4vM0=
    LIVEKIT_SECRET: AgBNdYQ4yiFvjIbNM5yhf9O6TAqsxDM8M1agRKUW24Ug2fZX8jsg5Y6ca/pzj5m0W7vz3uF8QRbfU51avb7FZsTz3F4AhYD7AdJ5kZEr5hdVQ/la7hOI3QsEw3xKBGskAYp//xKplD2eHphMx1IVdBQpdogAZADuMq5qbnZNsXEAOnG7eoiTPCTcfG5vYwV5MhSer+uCp22rlywUxMdlgGYZjfGDQwLn+prDImWYUqclPtdLXRzhNloR7CjRiv6nxwupWC5kVsWZH1nCUYF71neznO87JEHe5vK/Lf6Kj4ovxyUUKpsAnSzHAaQtWOQH3ssWdRHhHLnRE++SFFavNatz0UdxqxFYFvbt/X+iXwrQrd3y3hMBqt0o+YoI9EM4OpzfYGg9B9zwaTKoEgCS5f0bkXuqV90nPW7WqjRtgbfrohidoWkXCC7o7rll9coHYCBebKLn4McVJW0856Q6n59VzghUeIXidMzxktU8g8ZCxbtzIvfZ+s2kTAmvMQzWfJm94Q8Czaf9zFTnSEoN3HL3O7YicXL8dpLCLoHx7es33rICFZQQKDAktm8I3BUfRN9m+NWkZCXkDbIWIdOkuMNU5lCg4j7/QYHDmo+vy1iUf5xyr7y0BAWjEHh0sTq0TN5JQsbsKG6hPC7t960u6AH/kGWUYhkU3YlVtufgmG5viqyC5C/UJQxejlPwX+yhSN1nobmP8A0ffx95NVC2IoHZMFOYXCJIJ2sgJPUIqfd8ZtbB3hWMZbOvyE9Id3zyxDg=
  template:
    metadata:
      name: matrix-rtc-livekit
      namespace: dmz
    type: Opaque
