---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: dmz
spec:
  encryptedData:
    SEARXNG_SECRET: AgC2eQW2v4M+XlVyAb17q6YOGbjoDsflWcqSLoEEUgacyRovDlQEUnQlMGUZStK3tw/TCCywfyPdmhxi8XE3ikNFM9qRUSO2ILJhbQcQQnovnv4s+C2XFk7Mu1Ta2FwD0Iow5st4fvx13+KOe7cZJDw41XkX9yXMpNff1hNHUi5GP0shPN5wBVIezYyxJUzMjLUzQfS1sRJVHyn1eUkl07BajBXIpBxDsJHFaG94HDI3OkEUOSf0gcrBhtSFKn2ScWg6Soas3OBJTDgE+/9kThugcjzzGOBdffwZCPJhOJS4XsCSjzADpJcqFFebprLmAa2O7wpoULkX8Vd5/JU+36Lx3dRcvrVftoTMoBezor7O1sxqHzJgRU1gxtlDOd3z2GoRNQxM8kOpfENrUqyx9yWv9UZrBcMuEJeb8m0kpZWpT+V1LNdlOSFkboAxxZ4BMjNn37ZWnN4w3vua7RCnYURZhY5sXD1R35zcGY7BD2kkdeJT5PUa0Mz+D/n6IhUIZ9/9XJFMcvPCuqg/7rzfCK1OMxsYSZkJr9oyNVxUzUTws0lAtjTXPX0Pld4r/cuGaJFfhtqVRj62YZxH68nVd48R1GKjLYzymD6bTCyc9RWabF8w3ZV5MK9grANcW2p7ZB7Fd/DyaZje9JOtGSMYZWsPaRNhgRvfnLT8/JuV50+oqVOzKO2Ygb1gaDxw6vfLwwDK1fFSlwaxgbRWgxuaVkmD9MhUGHGFLv3jNfYjcHpfcLIK7LqayFB+BkoVaUw/iSM=
  template:
    metadata:
      name: searxng-secret
      namespace: dmz
