---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-sso
  namespace: dmz
spec:
  encryptedData:
    sso-client-id: AgBmReOCaKV6WgVU5CstIuPaHzTEXT3MvFCQnZMPPeiZpWhxUABnFPu/uvSwAWe7gYaBArPY+dS6ghldw5i2s22eNHl2GYSg2lAui5JvNJcGcZ/MyshNjeEMEv2yRJOxHNIFH3AAbvDVs+AXYVbQvTq/CpXU7DEnlaE6SWkaF8lyUlinyXYTrl2WwlG8StiUWOPNX4EiL7Xd39JA8huPU8n3Mx23ofZvENe8IbhY2V/+zXUKaxjJQiKXTrd0EYotLbXXUqg6Yp3dqqdIrpIaIkEfm9Qy7dj7CCrpFsmdrhtw0LjxSQ5Bz7dwac6Ikqb0qd0Zjsh/4+GyLMkhCe3R1M1iMFTxAhd2aoRZjjIDBszkzEOaeLeZZ0+5lLo0ahDCTUpiCReY4GpbGvajdEE9vo574qhEdQ70mXFQY8emKBlyjuNdVK4CSnKzxQ4M6EPqiLxaJuKifyrr8DXzOTQPcfF4kH9W2Wd2GiNj6WWKXtvLeNp+8oITbXgYpSnbBegh58sIr6GvT2Itrwv3Amzno4sHVnpki41R8Mv3QZG+tyMZr1CPLKoSYPmHXynjTSIIxyvHDu1ldEwQJVY8iLuI2/NHS1MPDDojI5daZKwKjib2CYo9zsk7NPcYO5+V1Zp15Gu818S4vnKvbCMGzdEH8665z3uqv1On4ibCDV3WJzGGflsEGD2A24P5oCU67ft1GR6Nm9cVrTLaHl0vyYsjcslj/P5rZRf0XJXEHJr/wLWdOZMARK+z0Fl7
    sso-client-secret: AgCove/I4L2ETbxHQG2kOTxPLj4bSV1W3rjPp9SpEZlNbEQWVzMNK3oATrpaZfKqo0aWEoU0BxP6csNSzlPFOLtkLw2ZImKUxdaDtvgzEVZW6cPBgMjQSognGJBQJAUBHHlTWeupcaHWfpp4pOzYEbQD6rPZGd7vS/strYJorDWnKEkIZqYnozk0nSCajSJPrdjQqumYaGODJgTcsliXLlr9FRZykhi/BYPsX32dXWQl3Taqn2AHt//C8dUZqs3Pb4hVjI8unICGNbi9EPEEKOJXtrs0qup6EtSoWu2E6B+DRHruYuuq29+qH1HqYRADrkINtsTbItCIqWutHpVFVjzhoAojJXG3L1ftUenQvZlNKC4xUaLErarCoYaeFgBiHXBeUNzBn80EYNI98PGR+K7ZceYI/oKyaY87cbnWjf0l6YZw/YgwTKVnXKVUyS75Xm190RRF1QXchyusy+1PV3ljooo2AS1SB5WWbJqVmygHFHQ1aTX4cTvhArZV5w79xu3YpItjfpt1bg6dWYb0XjWBaIUKI2rFtc+3az+U6FpUaKeDCRe+G6B+fqUJBoR0X4rfXtjLYo2JzvYj/IqP5VlwbomYw8tr8E7nrpuUx5EUP2vxEvvaHdr9tjjKx4Ojmsiws27bPryPCZraPFfP8fc6N8WYtSR6zYHxJFwqwKgWnWTo3tDmIhbYoQR/cJP7lVkAIguUgRDF0Hd0hKlXQ5arTPbiy1rQjKhBWLo6VAKGuDz3mkNmyMd66cP1YgSF+6ALPGrKHKEQwbePIkfRyNBxBK/JQtZEbhTC9KmUQgij+RnFZ0EbL2IrTLAXXglYz2YZ3S/NAKFMp5rpSr6Yqvb+oVe4pIJxuRnsn7OXzqkJzA==
  template:
    metadata:
      name: vaultwarden-sso
      namespace: dmz
    type: Opaque
