---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-push
  namespace: dmz
spec:
  encryptedData:
    push-id: AgDLEFh9cpnMsNxcuiWDYgZDNCMLQpWmUMXuoLn/gMFkIKJb/gMU8jsYK3AqAFsEBJn7xY1xrKTgQ80iO2vS7N4TIHD3NAZj7VbH4XvWLsBO9XxKcVD2Rt3gFXU9mRb2Nhu+tBVohsC/32Is9bakO9Xvl4OOug5bfqcVMu/W77HPSHeAGtnfzn5OsJ7GSbr7v/HIPwPAEMESPE7yelfn+vprUjdzSJmzK76rptuwtYLKgnNyUHTdi4aIDD9x6RhquyhXctSMb2lStdFeFWm2cUNzdmjZkadpVR6/InFShAWy4KCJ8h1FmV9iYdhsoPu74UcZAEoAlk94Kqor8v9QQ0eGCdPO/kyCaxtR5lhmf/FxWF1Th/T+hw791yt3cOu72d/gzvOMM5hFpzBlUFybpFnaVdpf+XGwsnyyPvLc8hpzufQ1sNYvDd5b6OoZJwzYLRr6SHB3lODFU4YlBl3ipWhXXb1VLXkuETBwXOcgaCE8ARwkzuRru5ZWMKUwLrl2BDzykQ5crUKQhgao1HX0T+OO3DaCINlPW3p3ORZaXcP5wTQt9U7uJ3P/R8yoE+/0U11hhE0hSf/HJ5H0SK6SbjDZwXkG9IHnCggj19u7zofbH2iH3wQP0umHDEf0knPBIk/zKg69qrTpPOK6FHJZUTO5M+tOhHzxQFvL+tR+qBMlmeoquUZC/cP7FVKESYafd9jVD1exyTMjYRnWE125E2jsRoPwcIHnCalX0If7O3vY8EP3mdc=
    push-key: AgCx0yI/JT+CfSHCxNWSJVdX6TOrENuBHYSG4O+xlnyP2MbIAcGyj1uPLhkPpO3BLha/Jxo8fjVm/uTNgtIeGHDeBs9Do6NIeb3FeyPfFdJxZh+zAxKPH9L//sylCeoSuGH1GirDSgqbladlMNe7QpjSSFSIjLNUdRMRm4RFSXW203Zs2FNOamgJO5qNdwVBpPPtDoO7mmyUjql7a6xFAPN/z9Z88Lf9lm5TFB1f5aOLbWJVBmpCDsOU9hCsobm+4PMoY76NeTF3Sj4ch4TBmEFng04TXmi21hgmwsil53Co6VRyxSPzba+BWf4Md1/danD2CoOTU/qUlnC2m9tfZ/cGQRfwjNtnAzq8NMb/5TJRwwoINVubGsBkvNt3wowGWftoykokMfZhmgBn+E2YkQ0H4MkpbkkNZoaAH7CvTGP0GqLL72ipjIbiwz/CuVVDHm7LZbJqI66hznL12+gLMj1vEiVqlgYmnx8H9T+WVxEndhnLuAQsp4OsKrDANKO6Uxm7x2GwpM1dp6DjlSoxvie3X62rddNgIW+d0qBj1Vv3rRadSHOPD4GGErrXlLEGLJ2tE69gg9zBxIziydfdgT4kfDp/5NQ6oRHNDz/iOyltCbc3wUhA7U5cOIj6zThD8TILuVx+IhmbFK6EduGJ1BUHqP/r3qZqd5FwZP6NpqhSuJJ1OPRx65br1etGIFigLqYVbMPe8qeYa5oQRlcmi05Bl9m1zw==
  template:
    metadata:
      name: vaultwarden-push
      namespace: dmz
    type: Opaque
