---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-sso
  namespace: dmz
spec:
  encryptedData:
    sso-client-id: AgCLBPVRJYO0FRnbJbcVXjmt07/6/Y6V4vXHISS82ClFwH9cXzd+YkyBDIiaGKbdvxOs67zUsVc+K15hxy8/W1O0s75KqvDsSD1DUHt/IDlnTxyyQL/avqzLD4zmQd+f2ZdVglvCAEIRxqN4o1d5lgE6SI4c1VxBAglbMT+8rYSKqkbyigHsklAaof+hSRMfmAn6lujWooc1ZWfggZPBPC5pMoYzAh4l6VvS1lvZIyXfgp+sqOHdyt2j/XLT3YHIGIdTEXRejZh5LSJzEWcNw7LlpFSKbIKQSzRHhhzGsiShqYCzI2rGW60dB4MmSrVwhezE+0lGBcbb8mwBYOjaPLfnsCFe/gDMKLyiqLs0etWwcB+Zk/bhw+UrdL4K0r/FAWV+MDukOwt1s3UxtjwtdQglnBzjJP8alVpYDXSVUIvmTu5CXR1ijADOlN2UCIVD/JP+hlCGKSsIwAgjpxaVp2KEMAfhCSVBC2+X/KPqOvc+8w6Tc8rNJUKB0DHMrtgf6q8YfCcedSQDStfR97TnVVXdL/rQ8eZNDoMmXeww+l550GFZIhEC0gLjJn8tv2oBN/2y2F+F3pseTLPcEdFRTMBviTfyvWpuTJsMXjt49mT2Ke1hP+xkw8tayXmzVHh8inI7nNte0Hw5YE2aNqL4f+gJokLEwOKG3e3hoFr/wEs6kaTi5Eqm42+XWDbUF1rPGW1R2F9d0uALUmaI5rfxb/uV1kl8C+O8wR/cw41ixMezL3VtIIRg7YRk
    sso-client-secret: AgBtndGuwDV6E2TSc8gdU7eyNMJgg+RzxzIq0kHsKhRx7YW2g75rpr9b4Zwduf+Qv9Og5qqRSu27Cd2oj0ynDN8F7NRHT3smg2JAYbtm4kICKh2zlqNSXbi+vE1Ds6UZauhBCk/aNb4dYqhtFz0WssmYbBMLvWFDxwjI6jvrgvJF7nYrOZJdIHm6mjbmGBpOvY8MDSmzn5X75mgsTungpXkf+895l/mQo3ZMoB+U7qGj53s4wYxmmsNH5Zo3v6UDxx+uMp2/Uxd4nH3FYcLUrPFJSEMNjvCtrk7T+ya540fsAPCXvwJpBUMwCIl5rjZMMpj91r93QsGKYChvUS33Rc4TmpGsgR0c6IsmRefEPcLDsmTpy6MwkNIqhYeLqpoZ5PFHueZt/nAM+vbxIJJNsFdhfNzKuNNiIJY2kalxfQQo8UbGujNJaqOVyumnClztrDarpcPizXhVbpJD858ySa3HC9oz93cgCnka2AKrZLKZK65YLRDhYqxfGar18Cr/iZiV+2zITXAfwkRYtt5o9cEo4xCWSl6yJxP2R+wbP2ZXpvKgnuzQ3eIuA7NfexvRcfLAU+xSygWdtAdyvU14HezsNcb9OmkPhuZLJxNYpmaNXB0C5XYVXTksu5uGt1xZqypZAAtYUjUfN8ZMpdGpDsyOM52t1Rf9dHK/fFQHLcWhCri6VFXkDGlFS/TlcGfXFNoYGfkFlXqIbvClaws7JFM2+1j4MOalSHl32O0e4PKaYyO+cKOfzw84jW1s9mgUrfBbDMxbLwr3AmobgoRLFCV1p45UbtHaCBTldQMITwIa8xURaawW+VXb5tRHpbpg4vI4OGt8+ufX5tIaN03XPxSOgW+J1gS2/zHrinZqZ4D27w==
  template:
    metadata:
      name: vaultwarden-sso
      namespace: dmz
    type: Opaque
