---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-smtp
  namespace: dmz
spec:
  encryptedData:
    smtp-password: AgBQwv8FfvRX2PPqwwqr/atlmJD+ZkzfIEuvdZuyq3sDWibVJpLKKNO9aa8Gfp55A6UeBgq6eXBCd6XkPfM3PVHDR9dXpBW9tkTwJp62NIh9Z8nANifapv/d01G6ArXyo6vUQagYyV75UlSkiq+me+wOEev7TzzCuQpWi3fj7qyv5w99aYHB/8ZRNUxCPh9YB3pQOeVzQOyfcJjLNF4OzAAi0kCuwgcCOaPSsiipuXHW7NdIPKDt3lrbHzrDYUT/ts2SjpzvBEwWGdJWKMBNBdtn7AzuXTLAJBskR0mK4wRwgCk3hI88jDmx0ra0zCBQmU2gFxkhfhd2XUv2ZSqr2nLCiGCisHWkchYhI5VHrkRAsaA3dQIm2pUFv4aj6l6sNOZlOFHa2AbyTQ6i38X/g2hFgd24Va1HSVv6SSeWU6H+q3j6z+KFIPTrSEHxC3wdKQpt8d9bgEJC/C5AQ/gouVZJYFcAPlJ3FE/XwEH8G4rRbt9caWVCyPAB45K66vL431PdSZiH/bSmNx11ZZ7EjZD9QrLLbCzf1x4WM7jz6NxrczLU6qfAUk/6scVKYCnc9JFhpGyY/8KFZGW+pvOG/liAH2daYgYJNByEqDoBrHF9SPleYqzHxAWg7JHhSDnAYHocJTe6YrYtJ0EJyZZPRbkx+gMY5rCsVcAHFPrx6QGDtIu/dEI9vU0TrAQKZXQgADO5WbS0/0cFuwicWUMFZ10tX6rm+dzJqhWkpZyuKFl1Esg4ais=
    smtp-user: AgA5BnT18Ivx79a6wddHTnMZg1CiViNRhAUf2O7owpe2zI0RjtttnoqvPCSrfFr3sxAE79wc8QetSD737ffPNpFq0ssOho/bNAEfI2ZlkkS1XCKMu2ev7iDrdJVPfdyan+vcJutM4uAUzEt484cV1FqnmjhqFwN0pbe0VkGWr8pBfqM/f/1gC7xDTHPyd2UhqeBZ90ODmTSjHrd6CpNs5OEc5i9plX3ZWGYgZZgChS+5IOVvcoomXA8A4SYQJvGgJoh8HI6+I5ROVI2oO6kx+YcjvskF2o6cpJSPUJ0Qof3HD0kPvo/WcEP7gyRV4ogMkz93Jg30/j3e+k+KUfwyHVTYzmgwPYzNpsAa5kLPlramf5/EPVI+1JW0ApIe1YvYxWSF/1KkFYItnR+kH1rB9Dg2TGErbq/yGH0BoHbX86z7UAwlopF66tt49UaC3ewefwDFgVMbu+83PMn2KwbFgDCS6FHi24RP2ucvBUwilQzBS0I8uYCfY4wyUoVTCmYIOfsxaj6OBptlE+9VblYqqTMfKypwYOagsjSlqREOToMk3q0hxdK79HZB3N9xZ+A4bV3A0ERiw5GQou5JyWrqlLkGuPxRW4+12Q67e1ldMuLBaz1l81lFqgU7taaQohKIfSU3HX14e6G9Z0/Rftl9OzDoUxYcMYHuntFsoviqLqRfPj8ZyD+WkrrAM3GPu3kCvdNAIJbN1E4=
  template:
    metadata:
      name: vaultwarden-smtp
      namespace: dmz
    type: Opaque
