---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin
  namespace: dmz
spec:
  encryptedData:
    admin-token: AgCtonmZqqaMY4sADsepCPMVLQWbrKEMMTtaaY7RKHKEvoFKHLvqtIOoAa+3HR+96e0PR3szvwOHVJUsTggxfXzwDZM6kI5HvjEKrCG6bpGXzoUHGSxUmrJS+Ox5M7J6FproEa8OqB7kCldPCfa7M5q7eu2Tt7Ka4+65FXh7W5iWXEVYXrRvNvfqGafLHZ0kGE8796jsRyhPAiN8AJxASdlJVsPOUK8fWkHT75TZ1BYtPwq6l1cQGGER5j3gg6vz2bE15KXKG4VUFfNvAga1Dg3R+HzMGIqINRb3KxEQXUj+JK2tQVcUcgnkOTCMA4FQOzf3ZSG0p0Stn3elATyODpm+CgVLVPLH6CcUAQBvL44wXzwGnzrZS80f20uduXyWbyUjmXnCQjrrt/hbFww9qH9guUFKP7Zn5rr45dEQJSZ8pjfSQrNmSA+prLDS+tNoJ/I6FEe0Q+ixZ+ijYQbtHNuXZNYPZ0Ufn/iCmxF26ggu1oRhtD9/BVlSxkV4YzKjon1jzlsDWxDlhvF+0uoL5n/iIs/AmCG4ppPoBSqrSUXl5cCj2t0XG6fy/WpDGp3S56bjtuGQo5GGkDhxtkPqh11VJdqTEhpcxlDLuxjlaGjPDeS09xU3BJQ3RzjWWCc924f02P4ky+UcFpxONUTQY7qk9N+NfclTeZIT82e08WiZ5PXa7X6mZBCUfY51Apt7/iCtRVEwM60/22Tay5EUspbDkHT4GziSXSxmf4IiB3TwDhBDVqseaxC/OVZnZ4CAPGVswVxBp2m1psfxo2JbcUuPyzcIQALf0MY7HU9ag4EKpZ5ZP8lE300nysiMFbT5uyDI
  template:
    metadata:
      name: vaultwarden-admin
      namespace: dmz
    type: Opaque
