---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: private
  source:
    repoURL: https://github.com/bananamaker123/homelab-k8s.git
    targetRevision: HEAD
    path: apps/private/immich-postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
