apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-postgresql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '1'
    argocd-image-updater.argoproj.io/image-list: postgresql=pgvector/pgvector:pg17
    argocd-image-updater.argoproj.io/postgresql.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: private
  source:
    repoURL: https://github.com/mysweetpea/homelab-k8s.git
    targetRevision: HEAD
    path: apps/private/immich-postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
