---
global:
  security:
    allowInsecureImages: true
image:
  repository: pgvector/pgvector
  tag: "pg17"
auth:
  username: immich
  database: immich
  existingSecret: immich-postgresql
  secretKeys:
    adminPasswordKey: postgres-password
primary:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 8Gi
  service:
    type: ClusterIP
    port: 5432
readReplicas:
  replicaCount: 0
