apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-synapse
  namespace: argocd
spec:
  destination:
    namespace: dmz
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://ananace.gitlab.io/charts
      chart: matrix-synapse
      targetRevision: "3.12.30"
      helm:
        values: |
          serverName: mysweetpea.cc
          publicServerName: matrix.mysweetpea.cc
          wellknown:
            enabled: true
          ingress:
            enabled: false
          postgresql:
            enabled: true
            auth:
              password: synapse
              username: synapse
              database: synapse
          redis:
            enabled: true
            password: synapse-redis-2026
          extraConfig:
            max_upload_size: 50M
    - repoURL: https://github.com/mysweetpea/homelab-k8s.git
      path: apps/dmz/matrix-synapse
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
