apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-synapse
  namespace: dmz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-synapse
  template:
    metadata:
      labels:
        app: matrix-synapse
    spec:
      containers:
      - name: synapse
        image: ghcr.io/element-hq/synapse:v1.153.0
        ports:
        - containerPort: 8008
          name: http
        - containerPort: 8448
          name: federation
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: matrix-synapse-postgresql
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: matrix-synapse-postgresql
              key: REDIS_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: matrix-synapse
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-synapse
  namespace: dmz
spec:
  selector:
    app: matrix-synapse
  ports:
  - port: 8008
    targetPort: 8008
    name: http
  - port: 8448
    targetPort: 8448
    name: federation
