serverName: mysweetpea.duckdns.org
reportStats: false
postgresql:
  enabled: false
externalPostgresql:
  host: matrix-synapse-postgresql.dmz.svc.cluster.local
  port: 5432
  database: synapse
  username: synapse
  existingSecret: matrix-synapse-postgresql
  existingSecretPasswordKey: password
redis:
  enabled: false
externalRedis:
  host: matrix-synapse-redis-master.dmz.svc.cluster.local
  port: 6379
  existingSecret: matrix-synapse-postgresql
  existingSecretPasswordKey: REDIS_PASSWORD
persistence:
  enabled: true
  existingClaim: matrix-synapse
signingkey:
  job:
    enabled: false
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 2Gi
