---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-rtc
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mysweetpea/homelab-k8s.git
    targetRevision: HEAD
    path: apps/dmz/matrix-rtc
  destination:
    server: https://kubernetes.default.svc
    namespace: dmz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
