apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-lh
  namespace: private
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
