---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-proxy-outpost-token
  namespace: private
spec:
  encryptedData:
    token: AgB6z8oQmH0fp5eZ03qnJcvLKrusLO8YiJnoYUkzRbEW9BI3Fk4VmKNI9Cj+/1i+RKFgw2lGfKBs4QHKORPJs9M+Ackj1+yylyWJDRpuN1zYeR4o1nZM6aTTbtkh5r21fGGpK40d8NL+cBPzF3itgtCd37RxkOXHJtu520wdfLxjf1rSVxl0gi/f8u+UiBCM3O5p6NKFuawtkmbAMft7H1e8EvcU8NT/e/RCMXYn+AhwphRjxj0R2Lb2QrOLMsuHUehsrt3N52/RPEZO6zzTm+qda6PjMolJ/lJjQ06znvk6QWihvX1XKmIWAyh+C4uJFXmevkF+vDO2nJw9pr1ckcq1gJZz5/QBWsVs/P14UzHMl9fKgS08052JsDuEkSP9oBnu2I7I2KbtGjDg1o+5ZA1NhzUlpqd4OUxoTEmI3CJMqamRv1ERNs++SfiCPHqBjyB005OZqCcIokZCAvvhAPIXcKjbKizmDO43D5wAtAOLXxF0XUtG+kl5ttmoxCXwCsCb5dxKro4W7hFVZqvG/26Fzf0BHDvU5myXMJOjR+ifMSLxiC/Rs077+//iAO+Nqd/wLQy5xCAYvjT0udu7KLo0m95EprSqtI/7r6dNc+7pnH55zCw0eUJIH7xNCMmIu22PHRX7qOHz9Huuelz9dboT86WgEx8JnNauzs4A5pXXtgqhbyNvMt4n8tXY62ym6BCVpEk/rdfstw6DbJaYTzlKdT5cPYMpjYc032hkejkLeEJZ4Fz8bnPIuQCBTTmO191dvCPGIlIEidkAc+8=
  template:
    metadata:
      name: authentik-proxy-outpost-token
      namespace: private
    type: Opaque
