volume:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClassName: longhorn
  existingClaim: uptime-kuma-pvc
image:
  tag: "2.5.1"
  repository: louislam/uptime-kuma
service:
  type: ClusterIP
  port: 3001
